package model.board;

import java.util.Iterator;
import java.util.Set;

import com.google.common.base.Optional;
import com.google.common.collect.ImmutableMultimap;
import com.google.common.collect.ImmutableSet;
import com.google.common.collect.Multimap;

import utilities.enumerations.CellType;
import utilities.enumerations.RoomCard;

/**
 * This class implements the Board interface. This class is immutable and a
 * BoardImpl object is generated by a BoardFactory instance (simple factory).
 */
public final class BoardImpl implements Board {

    private static final long serialVersionUID = -6359597920098113420L;
    private final int height;
    private final int width;
    private final ImmutableMultimap<RoomCard, Cell> rooms;
    private final ImmutableSet<Cell> hallway;

    // package level access (visibility)
    BoardImpl(final int height, final int width, final Multimap<RoomCard, Cell> rooms, final Set<Cell> hallway) {
        this.height = height;
        this.width = width;
        this.rooms = ImmutableMultimap.copyOf(rooms);
        this.hallway = ImmutableSet.copyOf(hallway);
    }

    @Override
    public int getHeight() {
        return this.height;
    }

    @Override
    public int getWidth() {
        return this.width;
    }

    @Override
    public Set<RoomCard> getRooms() {
        return this.rooms.keySet();
    }

    @Override
    public Set<Cell> getRoomCells(final RoomCard room) {
        return ImmutableSet.copyOf(this.rooms.get(room));
    }

    @Override
    public DoorCell getDoor(final RoomCard room) {
        return (DoorCell) this.rooms.get(room).stream().filter(cell -> cell.getType().equals(CellType.DOOR)).iterator()
                .next();
    }

    @Override
    public Optional<TrapDoorCell> getTrapDoor(final RoomCard room) {
        final Iterator<Cell> trapIterator = this.rooms.get(room).stream()
                .filter(cell -> cell.getType().equals(CellType.TRAP_DOOR)).iterator();
        if (trapIterator.hasNext()) {
            return Optional.of((TrapDoorCell) trapIterator.next());
        } else {
            return Optional.absent();
        }
    }

    @Override
    public Set<Cell> getHallwayCells() {
        return this.hallway;
    }

    @Override
    public int getDistance(final Position a, final Position b) {
        return Math.abs(a.getX() - b.getX()) + Math.abs(a.getY() - b.getY());
    }
}