package it.unibo.geometrybash.commons.pattern.observerpattern.modelobserver;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import it.unibo.geometrybash.commons.pattern.observerpattern.Event;

/**
 * A class that represent an event generated by the model and that is listened
 * by a model observer.
 *
 * <p>
 * The event type is represented using {@link ModelEventType}.
 * 
 * @see ModelObserver
 * @see Event
 */
public final class ModelEvent implements Event {

    /**
     * Logger useful for debug purposes.
     */
    private static final Logger LOGGER = LoggerFactory.getLogger(ModelEvent.class);

    /**
     * The type of event generated.
     * 
     * @see ModelEventType
     */
    private final ModelEventType type;

    private ModelEvent(final ModelEventType type) {
        this.type = type;
    }

    /**
     * A factory static method to create an event that represents a victory in the
     * model.
     * 
     * @return a instance of this class with type {@link ModelEventType#VICTORY}.
     */
    public static ModelEvent createVictoryEvent() {
        LOGGER.info("Created a new Victory Event");
        return new ModelEvent(ModelEventType.VICTORY);
    }

    /**
     * A factory static method to create an event that represents a gameover in the
     * model.
     * 
     * @return a instance of this class with type {@link ModelEventType#GAMEOVER}.
     */
    public static ModelEvent createGameOverEvent() {
        return new ModelEvent(ModelEventType.GAMEOVER);
    }

    /**
     * A method that returns the type of the event.
     * 
     * @return the {@link ModelEventType} of this instance.
     */
    public ModelEventType getType() {
        return type;
    }

    /**
     * A method that returns the name of the event.
     * 
     * @return the name of the type represented by this event.
     */
    @Override
    public String getEventName() {
        return type.getName();
    }
}
