import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    const val com_github_spotbugs_gradle_plugin: String =
            "com.github.spotbugs:com.github.spotbugs.gradle.plugin:" +
            Versions.com_github_spotbugs_gradle_plugin

    const val de_aaschmid_cpd_gradle_plugin: String =
            "de.aaschmid.cpd:de.aaschmid.cpd.gradle.plugin:" +
            Versions.de_aaschmid_cpd_gradle_plugin

    const val checkstyle: String = "com.puppycrawl.tools:checkstyle:" + Versions.checkstyle

    const val pmd_dist: String = "net.sourceforge.pmd:pmd-dist:" + Versions.pmd_dist

    const val pmd_java: String = "net.sourceforge.pmd:pmd-java:" + Versions.pmd_java

    const val spotbugs: String = "com.github.spotbugs:spotbugs:" + Versions.spotbugs
}
