package model.enemy;

import model.command.Command;

/**
 * 
 *Strategy for the command generations.
 */
public interface AiCommandGenerator {
    /**
     * 
     * @return a new commandd generated by a given strategy ruled by the implementation.
     */
    Command generateNextCommand();

}
