package it.unibo.the100dayswar.commons.utilities.api;

import java.io.Serializable;

import it.unibo.the100dayswar.commons.patterns.Observable;
import it.unibo.the100dayswar.commons.patterns.Observer;

/**
 * An interface for all the objects that can generate resources.
 */
public interface ResourceGenerator extends Observable<ResourceGenerator>, Serializable {
    /**
     * Get the amount of resources generated by the object.
     * 
     * @return the amount of resources generated
     */
    int getAmount();
    /**
     * Notify the observer that the object has generated resources.
     * 
     * @param observer the observer to notify
     */
    void notify(Observer<ResourceGenerator> observer);
    /**
     * Add an observer to the object.
     * 
     * @param observer the observer to add
     */
    @Override
    void attach(Observer<ResourceGenerator> observer);
    /**
     * Remove an observer from the object.
     * 
     * @param observer the observer to remove
     */
    @Override
    void detach(Observer<ResourceGenerator> observer);
}
