/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package it.unibo.javadyno;

import it.unibo.javadyno.controller.api.Controller;
import it.unibo.javadyno.controller.impl.ControllerImpl;
import it.unibo.javadyno.view.impl.MainMenu;

/** Main application entry-point's class. */

public final class App {
    private App() { }

    /**
     * Main application entry-point.
     *
     * @param args passed to JavaFX.
     */
    public static void main(final String[] args) {
        final Controller controller = new ControllerImpl();
        MainMenu.setController(controller);
        controller.launchApp(args);
    }
}
