package ryleh.model.components;

import ryleh.model.GameObject;
import ryleh.model.World;
/**
 * Abstract implementation of Component. All components should extend this class.
 */
public abstract class AbstractComponent implements Component {
    /**
     * Id generated by the world at the moment this Component is instantiated.
     */
    private String id;
    /**
     * The Object to which this component is added.
     */
    private GameObject object;
    /**
     * The World where this component is instantiated.
     */
    private final World world;

    /**
     * 
     * @param world The world where the possessor of this component is added.
     */
    public AbstractComponent(final World world) {
        super();
        this.world = world;
        id = world.generateId("component");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void onAdded(final GameObject object) {
        this.object = object;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public abstract void onUpdate(double deltaTime);

    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        return "Component [id=" + id + "]";
    }

    /**
     * Gets this component ID.
     * 
     * @return id
     */
    public String getId() {
        return id;
    }

    /**
     * Sets this component ID.
     * 
     * @param id
     */
    public void setId(final String id) {
        this.id = id;
    }

    /**
     * Gets the Object to which this component is added.
     * 
     * @return Game object of this component.
     */
    public GameObject getObject() {
        return object;
    }

    /**
     * Get the World where this component is instantiated.
     * 
     * @return World of this component.
     */
    public World getWorld() {
        return world;
    }
}
