/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package buontyhunter;

import buontyhunter.core.GameEngine;

public class App {

    public static void main(String[] args) throws InterruptedException {
        while (true) {
            GameEngine engine = new GameEngine();
            engine.initGame();
        }
    }
}
