package controller.gui.tutorial;

public interface GUITutorialController {

    /**
     * The handler for the click event generated by the 'back' button.
     */
    void backBtnOnClickHandler();

}
