/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package casim;

import casim.core.Launcher;
import javafx.application.Application;
/**
 * Main project class.
 */
public final class App {
        /**
     * Entry point.
     * 
     * @param args command line args.
     */
    public static void main(final String[] args) {
        Application.launch(Launcher.class, args);
    }

    private App() {

    }
}
