package org.lkyhro.gui;

import org.lkyhro.Hero;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by Migani Luca on 20/02/2016.
 */
public class AdventureIntro {
    private JButton backButton;
    private JButton goButton;
    private JPanel introPanel;
    private int nMonster;
    private int nBossSlayed=0;
    private JLabel label1;
    private JLabel label2;
    private boolean isBoss;

    /**
     * Constructive method for AdventureIntro.
     *
     * @param initialGUI InitialGui is the first and principal gui of the program
     * @param hero Hero the hero used by the player
     * @param nBossSlayed int number of boss killed by hero
     * @param nMonster int number of monsters killed by hero in this adventure
     * @param isBoss Boolean to identify if the battle is with a boss or monster
     */
    public AdventureIntro(InitialGUI initialGUI, Hero hero, int nBossSlayed, int nMonster, boolean isBoss) {
        this.nBossSlayed=nBossSlayed;
        this.label2.setText("Level "+(nBossSlayed+1));
        this.nMonster=nMonster;
        this.isBoss=isBoss;
        if (this.isBoss){
            this.label1.setText("Boss Battle");
        }else if(!this.isBoss){
            this.label1.setText("Monster " + nMonster);
        }
        goButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                initialGUI.switchPanel(new MonsterBattle(initialGUI, hero, nBossSlayed, nMonster, isBoss).$$$getRootComponent$$$());
            }
        });
        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                initialGUI.switchPanel(new BaseGameMenu(initialGUI, hero).$$$getRootComponent$$$());
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        introPanel = new JPanel();
        introPanel.setLayout(new GridBagLayout());
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        gbc.ipadx = 200;
        introPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipady = 150;
        introPanel.add(spacer2, gbc);
        label1 = new JLabel();
        label1.setFont(new Font(label1.getFont().getName(), label1.getFont().getStyle(), 14));
        label1.setText("Monster "+nMonster);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.SOUTHEAST;
        introPanel.add(label1, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        introPanel.add(spacer3, gbc);
        goButton = new JButton();
        goButton.setText("Go");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        introPanel.add(goButton, gbc);
        backButton = new JButton();
        backButton.setText("Back");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        introPanel.add(backButton, gbc);
        label2 = new JLabel();
        label2.setFont(new Font(label2.getFont().getName(), label2.getFont().getStyle(), 14));
        label2.setText("Level "+(nBossSlayed+1));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        introPanel.add(label2, gbc);
    }

    /**
     *
     * @return JComponent the major panel of this class
     */
    public JComponent $$$getRootComponent$$$() {
        return introPanel;
    }
}
