package org.lkyhro.gui;

import org.lkyhro.Hero;
import org.lkyhro.savemanager.SaveManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;

/**
 * Created by Migani Luca on 19/02/2016.
 */
@SuppressWarnings("serial")
public class BaseGameMenu extends JComponent {
    /**
	 * 
	 */
	private JPanel BaseGameMenuPanel;
    private JPanel ButtonPanel;
    private JButton adventureButton;
    private JButton savingButton;
    private JButton heroButton;
    private JButton exitButton;

    /**
     * Constructor method for BaseGameMenu
     * @param initialGUI InitialGui InitialGui is the first and principle gui of the program
     * @param hero Hero the hero used by the player
     */
    public BaseGameMenu(InitialGUI initialGUI, Hero hero) {
        adventureButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
        exitButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });
        adventureButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                initialGUI.switchPanel(new AdventureIntro(initialGUI, hero, hero.getnBossSlayed(), 1, false).$$$getRootComponent$$$());
            }
        });
        heroButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                initialGUI.switchPanel(new HeroDisplay(initialGUI, hero).$$$getRootComponent$$$());
            }
        });
        savingButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    SaveManager saveManager = new SaveManager("fileSave.txt");
                    saveManager.saveGame(hero);
                    JOptionPane.showMessageDialog(BaseGameMenuPanel,
                            "Game Saved!", "Lucky Hero", JOptionPane.INFORMATION_MESSAGE);
                } catch (IOException e1) {
                    e1.printStackTrace();
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        BaseGameMenuPanel = new JPanel();
        BaseGameMenuPanel.setLayout(new BorderLayout(0, 0));
        BaseGameMenuPanel.setBorder(BorderFactory.createTitledBorder("BaseMenu"));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        BaseGameMenuPanel.add(panel1, BorderLayout.CENTER);
        panel1.setBorder(BorderFactory.createTitledBorder("What you Want to do?"));
        ButtonPanel = new JPanel();
        ButtonPanel.setLayout(new GridBagLayout());
        panel1.add(ButtonPanel, BorderLayout.CENTER);
        adventureButton = new JButton();
        adventureButton.setOpaque(false);
        adventureButton.setPreferredSize(new Dimension(150, 100));
        adventureButton.setText("Adventure");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ButtonPanel.add(adventureButton, gbc);
        heroButton = new JButton();
        heroButton.setPreferredSize(new Dimension(150, 100));
        heroButton.setText("Hero");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ButtonPanel.add(heroButton, gbc);
        savingButton = new JButton();
        savingButton.setPreferredSize(new Dimension(150, 100));
        savingButton.setText("Save");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ButtonPanel.add(savingButton, gbc);
        exitButton = new JButton();
        exitButton.setPreferredSize(new Dimension(150, 100));
        exitButton.setText("Exit");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ButtonPanel.add(exitButton, gbc);
    }

    /**
     *
     * @return JComponent the major panel of this class
     */
    public JComponent $$$getRootComponent$$$() {
        return BaseGameMenuPanel;
    }
}
