package org.lkyhro.gui;

import org.lkyhro.savemanager.SaveManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;

/**
 * Created by Migani Luca on 18/02/2016.
 */
public class StartMenu {
    private JPanel majorPanel;
    private JButton newGameButton;
    private JButton exitGameButton;
    private JButton continueButton;
    private JPanel buttonPanel;



    /**
     * Constructor method for StartMenu
     * @param initialGUI InitialGui is the first and principal gui of the program
     */
    public StartMenu(InitialGUI initialGUI) {

        newGameButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                initialGUI.switchPanel(new NameSelection(initialGUI).$$$getRootComponent$$$());
            }
        });
        continueButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {

                    File f = new File("fileSave.txt");
                    if (f.isFile()) {
                        SaveManager saveManager = new SaveManager("fileSave.txt");
                        initialGUI.switchPanel(new BaseGameMenu(initialGUI, saveManager.loadGame()).$$$getRootComponent$$$());
                    } else {
                        JOptionPane.showMessageDialog(buttonPanel,
                                "No previous saving file found!",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                    }
                } catch (IOException e1) {
                    e1.printStackTrace();
                }
            }
        });
        exitGameButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        majorPanel = new JPanel();
        majorPanel.setLayout(new GridBagLayout());
        buttonPanel = new JPanel();
        buttonPanel.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        majorPanel.add(buttonPanel, gbc);
        exitGameButton = new JButton();
        exitGameButton.setText("Exit Game");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        buttonPanel.add(exitGameButton, gbc);
        newGameButton = new JButton();
        newGameButton.setText("New Game");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        buttonPanel.add(newGameButton, gbc);
        continueButton = new JButton();
        continueButton.setText("Continue");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        buttonPanel.add(continueButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        gbc.ipady = 10;
        majorPanel.add(spacer1, gbc);
        final JLabel label1 = new JLabel();
        label1.setFont(new Font("Malgun Gothic", Font.ITALIC, 14));
        label1.setHorizontalAlignment(0);
        label1.setHorizontalTextPosition(0);
        label1.setText("Lucky Hero");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        majorPanel.add(label1, gbc);
    }

    /**
     * @return JComponent the major panel of this class
     */
    public JComponent $$$getRootComponent$$$() {
        return majorPanel;
    }
}
