/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Indexes;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Keys;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Trustalo;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records.CasemodelsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Casemodels extends TableImpl<CasemodelsRecord> {

    private static final long serialVersionUID = 1213954752;

    /**
     * The reference instance of <code>trustalo.casemodels</code>
     */
    public static final Casemodels CASEMODELS = new Casemodels();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CasemodelsRecord> getRecordType() {
        return CasemodelsRecord.class;
    }

    /**
     * The column <code>trustalo.casemodels.ID</code>.
     */
    public final TableField<CasemodelsRecord, UInteger> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>trustalo.casemodels.Color</code>.
     */
    public final TableField<CasemodelsRecord, UByte> COLOR = createField("Color", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>trustalo.casemodels</code> table reference
     */
    public Casemodels() {
        this(DSL.name("casemodels"), null);
    }

    /**
     * Create an aliased <code>trustalo.casemodels</code> table reference
     */
    public Casemodels(String alias) {
        this(DSL.name(alias), CASEMODELS);
    }

    /**
     * Create an aliased <code>trustalo.casemodels</code> table reference
     */
    public Casemodels(Name alias) {
        this(alias, CASEMODELS);
    }

    private Casemodels(Name alias, Table<CasemodelsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Casemodels(Name alias, Table<CasemodelsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Trustalo.TRUSTALO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CASEMODELS_CASEMODELSCOLORFK, Indexes.CASEMODELS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CasemodelsRecord> getPrimaryKey() {
        return Keys.KEY_CASEMODELS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CasemodelsRecord>> getKeys() {
        return Arrays.<UniqueKey<CasemodelsRecord>>asList(Keys.KEY_CASEMODELS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CasemodelsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CasemodelsRecord, ?>>asList(Keys.CASEMODELSIDFK, Keys.CASEMODELSCOLORFK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Casemodels as(String alias) {
        return new Casemodels(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Casemodels as(Name alias) {
        return new Casemodels(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Casemodels rename(String name) {
        return new Casemodels(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Casemodels rename(Name name) {
        return new Casemodels(name, null);
    }
}
