/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Indexes;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Keys;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Trustalo;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records.ColorsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Colors extends TableImpl<ColorsRecord> {

    private static final long serialVersionUID = -256680339;

    /**
     * The reference instance of <code>trustalo.colors</code>
     */
    public static final Colors COLORS = new Colors();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ColorsRecord> getRecordType() {
        return ColorsRecord.class;
    }

    /**
     * The column <code>trustalo.colors.ID</code>.
     */
    public final TableField<ColorsRecord, UByte> ID = createField("ID", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>trustalo.colors.HexCode</code>.
     */
    public final TableField<ColorsRecord, String> HEXCODE = createField("HexCode", org.jooq.impl.SQLDataType.CHAR(6).nullable(false), this, "");

    /**
     * Create a <code>trustalo.colors</code> table reference
     */
    public Colors() {
        this(DSL.name("colors"), null);
    }

    /**
     * Create an aliased <code>trustalo.colors</code> table reference
     */
    public Colors(String alias) {
        this(DSL.name(alias), COLORS);
    }

    /**
     * Create an aliased <code>trustalo.colors</code> table reference
     */
    public Colors(Name alias) {
        this(alias, COLORS);
    }

    private Colors(Name alias, Table<ColorsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Colors(Name alias, Table<ColorsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Trustalo.TRUSTALO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.COLORS_HEXCODE, Indexes.COLORS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ColorsRecord, UByte> getIdentity() {
        return Keys.IDENTITY_COLORS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ColorsRecord> getPrimaryKey() {
        return Keys.KEY_COLORS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ColorsRecord>> getKeys() {
        return Arrays.<UniqueKey<ColorsRecord>>asList(Keys.KEY_COLORS_PRIMARY, Keys.KEY_COLORS_HEXCODE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Colors as(String alias) {
        return new Colors(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Colors as(Name alias) {
        return new Colors(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Colors rename(String name) {
        return new Colors(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Colors rename(Name name) {
        return new Colors(name, null);
    }
}
