/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Indexes;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Keys;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Trustalo;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records.ContactsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Contacts extends TableImpl<ContactsRecord> {

    private static final long serialVersionUID = -125093251;

    /**
     * The reference instance of <code>trustalo.contacts</code>
     */
    public static final Contacts CONTACTS = new Contacts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContactsRecord> getRecordType() {
        return ContactsRecord.class;
    }

    /**
     * The column <code>trustalo.contacts.Category</code>.
     */
    public final TableField<ContactsRecord, UByte> CATEGORY = createField("Category", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>trustalo.contacts.Person</code>.
     */
    public final TableField<ContactsRecord, UInteger> PERSON = createField("Person", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>trustalo.contacts.Value</code>.
     */
    public final TableField<ContactsRecord, String> VALUE = createField("Value", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>trustalo.contacts.ID</code>.
     */
    public final TableField<ContactsRecord, UInteger> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * Create a <code>trustalo.contacts</code> table reference
     */
    public Contacts() {
        this(DSL.name("contacts"), null);
    }

    /**
     * Create an aliased <code>trustalo.contacts</code> table reference
     */
    public Contacts(String alias) {
        this(DSL.name(alias), CONTACTS);
    }

    /**
     * Create an aliased <code>trustalo.contacts</code> table reference
     */
    public Contacts(Name alias) {
        this(alias, CONTACTS);
    }

    private Contacts(Name alias, Table<ContactsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Contacts(Name alias, Table<ContactsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Trustalo.TRUSTALO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CONTACTS_CATEGORYVALUEUNIQUE, Indexes.CONTACTS_CONTACTSPERSONFK, Indexes.CONTACTS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ContactsRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_CONTACTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContactsRecord> getPrimaryKey() {
        return Keys.KEY_CONTACTS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContactsRecord>> getKeys() {
        return Arrays.<UniqueKey<ContactsRecord>>asList(Keys.KEY_CONTACTS_CATEGORYVALUEUNIQUE, Keys.KEY_CONTACTS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ContactsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ContactsRecord, ?>>asList(Keys.CONTACTSCONTACTCATEGORIESFK, Keys.CONTACTSPEOPLEFK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Contacts as(String alias) {
        return new Contacts(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Contacts as(Name alias) {
        return new Contacts(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Contacts rename(String name) {
        return new Contacts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Contacts rename(Name name) {
        return new Contacts(name, null);
    }
}
