/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Indexes;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Keys;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Trustalo;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records.DevicestatesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Devicestates extends TableImpl<DevicestatesRecord> {

    private static final long serialVersionUID = 1238516687;

    /**
     * The reference instance of <code>trustalo.devicestates</code>
     */
    public static final Devicestates DEVICESTATES = new Devicestates();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DevicestatesRecord> getRecordType() {
        return DevicestatesRecord.class;
    }

    /**
     * The column <code>trustalo.devicestates.ID</code>.
     */
    public final TableField<DevicestatesRecord, UByte> ID = createField("ID", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>trustalo.devicestates.Name</code>.
     */
    public final TableField<DevicestatesRecord, String> NAME = createField("Name", org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>trustalo.devicestates.Description</code>.
     */
    public final TableField<DevicestatesRecord, String> DESCRIPTION = createField("Description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>trustalo.devicestates</code> table reference
     */
    public Devicestates() {
        this(DSL.name("devicestates"), null);
    }

    /**
     * Create an aliased <code>trustalo.devicestates</code> table reference
     */
    public Devicestates(String alias) {
        this(DSL.name(alias), DEVICESTATES);
    }

    /**
     * Create an aliased <code>trustalo.devicestates</code> table reference
     */
    public Devicestates(Name alias) {
        this(alias, DEVICESTATES);
    }

    private Devicestates(Name alias, Table<DevicestatesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Devicestates(Name alias, Table<DevicestatesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Trustalo.TRUSTALO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DEVICESTATES_NAME, Indexes.DEVICESTATES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DevicestatesRecord, UByte> getIdentity() {
        return Keys.IDENTITY_DEVICESTATES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DevicestatesRecord> getPrimaryKey() {
        return Keys.KEY_DEVICESTATES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DevicestatesRecord>> getKeys() {
        return Arrays.<UniqueKey<DevicestatesRecord>>asList(Keys.KEY_DEVICESTATES_PRIMARY, Keys.KEY_DEVICESTATES_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Devicestates as(String alias) {
        return new Devicestates(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Devicestates as(Name alias) {
        return new Devicestates(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Devicestates rename(String name) {
        return new Devicestates(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Devicestates rename(Name name) {
        return new Devicestates(name, null);
    }
}
