/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Indexes;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Keys;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Trustalo;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records.DevicerequestsdeviceswithidRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Devicerequestsdeviceswithid extends TableImpl<DevicerequestsdeviceswithidRecord> {

    private static final long serialVersionUID = 1475549611;

    /**
     * The reference instance of <code>trustalo.devicerequestsdeviceswithid</code>
     */
    public static final Devicerequestsdeviceswithid DEVICEREQUESTSDEVICESWITHID = new Devicerequestsdeviceswithid();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DevicerequestsdeviceswithidRecord> getRecordType() {
        return DevicerequestsdeviceswithidRecord.class;
    }

    /**
     * The column <code>trustalo.devicerequestsdeviceswithid.RequestDevice</code>.
     */
    public final TableField<DevicerequestsdeviceswithidRecord, UInteger> REQUESTDEVICE = createField("RequestDevice", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>trustalo.devicerequestsdeviceswithid.DeviceWithID</code>.
     */
    public final TableField<DevicerequestsdeviceswithidRecord, UInteger> DEVICEWITHID = createField("DeviceWithID", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>trustalo.devicerequestsdeviceswithid</code> table reference
     */
    public Devicerequestsdeviceswithid() {
        this(DSL.name("devicerequestsdeviceswithid"), null);
    }

    /**
     * Create an aliased <code>trustalo.devicerequestsdeviceswithid</code> table reference
     */
    public Devicerequestsdeviceswithid(String alias) {
        this(DSL.name(alias), DEVICEREQUESTSDEVICESWITHID);
    }

    /**
     * Create an aliased <code>trustalo.devicerequestsdeviceswithid</code> table reference
     */
    public Devicerequestsdeviceswithid(Name alias) {
        this(alias, DEVICEREQUESTSDEVICESWITHID);
    }

    private Devicerequestsdeviceswithid(Name alias, Table<DevicerequestsdeviceswithidRecord> aliased) {
        this(alias, aliased, null);
    }

    private Devicerequestsdeviceswithid(Name alias, Table<DevicerequestsdeviceswithidRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Trustalo.TRUSTALO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DEVICEREQUESTSDEVICESWITHID_PRIMARY, Indexes.DEVICEREQUESTSDEVICESWITHID_REQUESTDEVICESWITHIDDEVICEWITHIDFK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DevicerequestsdeviceswithidRecord> getPrimaryKey() {
        return Keys.KEY_DEVICEREQUESTSDEVICESWITHID_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DevicerequestsdeviceswithidRecord>> getKeys() {
        return Arrays.<UniqueKey<DevicerequestsdeviceswithidRecord>>asList(Keys.KEY_DEVICEREQUESTSDEVICESWITHID_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DevicerequestsdeviceswithidRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DevicerequestsdeviceswithidRecord, ?>>asList(Keys.REQUESTDEVICESWITHIDREQUESTDEVICEFK, Keys.REQUESTDEVICESWITHIDDEVICEWITHIDFK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Devicerequestsdeviceswithid as(String alias) {
        return new Devicerequestsdeviceswithid(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Devicerequestsdeviceswithid as(Name alias) {
        return new Devicerequestsdeviceswithid(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Devicerequestsdeviceswithid rename(String name) {
        return new Devicerequestsdeviceswithid(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Devicerequestsdeviceswithid rename(Name name) {
        return new Devicerequestsdeviceswithid(name, null);
    }
}
