/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Indexes;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Keys;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Trustalo;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records.DevicerequestsdevicemodelsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Devicerequestsdevicemodels extends TableImpl<DevicerequestsdevicemodelsRecord> {

    private static final long serialVersionUID = -1504443;

    /**
     * The reference instance of <code>trustalo.devicerequestsdevicemodels</code>
     */
    public static final Devicerequestsdevicemodels DEVICEREQUESTSDEVICEMODELS = new Devicerequestsdevicemodels();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DevicerequestsdevicemodelsRecord> getRecordType() {
        return DevicerequestsdevicemodelsRecord.class;
    }

    /**
     * The column <code>trustalo.devicerequestsdevicemodels.RequestDevice</code>.
     */
    public final TableField<DevicerequestsdevicemodelsRecord, UInteger> REQUESTDEVICE = createField("RequestDevice", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>trustalo.devicerequestsdevicemodels.DeviceModel</code>.
     */
    public final TableField<DevicerequestsdevicemodelsRecord, UInteger> DEVICEMODEL = createField("DeviceModel", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>trustalo.devicerequestsdevicemodels.Quantity</code>.
     */
    public final TableField<DevicerequestsdevicemodelsRecord, UShort> QUANTITY = createField("Quantity", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>trustalo.devicerequestsdevicemodels</code> table reference
     */
    public Devicerequestsdevicemodels() {
        this(DSL.name("devicerequestsdevicemodels"), null);
    }

    /**
     * Create an aliased <code>trustalo.devicerequestsdevicemodels</code> table reference
     */
    public Devicerequestsdevicemodels(String alias) {
        this(DSL.name(alias), DEVICEREQUESTSDEVICEMODELS);
    }

    /**
     * Create an aliased <code>trustalo.devicerequestsdevicemodels</code> table reference
     */
    public Devicerequestsdevicemodels(Name alias) {
        this(alias, DEVICEREQUESTSDEVICEMODELS);
    }

    private Devicerequestsdevicemodels(Name alias, Table<DevicerequestsdevicemodelsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Devicerequestsdevicemodels(Name alias, Table<DevicerequestsdevicemodelsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Trustalo.TRUSTALO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DEVICEREQUESTSDEVICEMODELS_PRIMARY, Indexes.DEVICEREQUESTSDEVICEMODELS_REQUESTDEVICEMODELSDEVICEMODELFK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DevicerequestsdevicemodelsRecord> getPrimaryKey() {
        return Keys.KEY_DEVICEREQUESTSDEVICEMODELS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DevicerequestsdevicemodelsRecord>> getKeys() {
        return Arrays.<UniqueKey<DevicerequestsdevicemodelsRecord>>asList(Keys.KEY_DEVICEREQUESTSDEVICEMODELS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DevicerequestsdevicemodelsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DevicerequestsdevicemodelsRecord, ?>>asList(Keys.DEVICEREQUESTSDEVICEMODELSREQUESTDEVICEFK, Keys.REQUESTDEVICEMODELSDEVICEMODELFK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Devicerequestsdevicemodels as(String alias) {
        return new Devicerequestsdevicemodels(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Devicerequestsdevicemodels as(Name alias) {
        return new Devicerequestsdevicemodels(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Devicerequestsdevicemodels rename(String name) {
        return new Devicerequestsdevicemodels(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Devicerequestsdevicemodels rename(Name name) {
        return new Devicerequestsdevicemodels(name, null);
    }
}
