/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Indexes;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Keys;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Trustalo;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records.DeviceswithidcomponentofdevicewithidRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Deviceswithidcomponentofdevicewithid extends TableImpl<DeviceswithidcomponentofdevicewithidRecord> {

    private static final long serialVersionUID = 1577721377;

    /**
     * The reference instance of <code>trustalo.deviceswithidcomponentofdevicewithid</code>
     */
    public static final Deviceswithidcomponentofdevicewithid DEVICESWITHIDCOMPONENTOFDEVICEWITHID = new Deviceswithidcomponentofdevicewithid();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DeviceswithidcomponentofdevicewithidRecord> getRecordType() {
        return DeviceswithidcomponentofdevicewithidRecord.class;
    }

    /**
     * The column <code>trustalo.deviceswithidcomponentofdevicewithid.ID</code>.
     */
    public final TableField<DeviceswithidcomponentofdevicewithidRecord, UInteger> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>trustalo.deviceswithidcomponentofdevicewithid.Compound</code>.
     */
    public final TableField<DeviceswithidcomponentofdevicewithidRecord, UInteger> COMPOUND = createField("Compound", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>trustalo.deviceswithidcomponentofdevicewithid.Component</code>.
     */
    public final TableField<DeviceswithidcomponentofdevicewithidRecord, UInteger> COMPONENT = createField("Component", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>trustalo.deviceswithidcomponentofdevicewithid</code> table reference
     */
    public Deviceswithidcomponentofdevicewithid() {
        this(DSL.name("deviceswithidcomponentofdevicewithid"), null);
    }

    /**
     * Create an aliased <code>trustalo.deviceswithidcomponentofdevicewithid</code> table reference
     */
    public Deviceswithidcomponentofdevicewithid(String alias) {
        this(DSL.name(alias), DEVICESWITHIDCOMPONENTOFDEVICEWITHID);
    }

    /**
     * Create an aliased <code>trustalo.deviceswithidcomponentofdevicewithid</code> table reference
     */
    public Deviceswithidcomponentofdevicewithid(Name alias) {
        this(alias, DEVICESWITHIDCOMPONENTOFDEVICEWITHID);
    }

    private Deviceswithidcomponentofdevicewithid(Name alias, Table<DeviceswithidcomponentofdevicewithidRecord> aliased) {
        this(alias, aliased, null);
    }

    private Deviceswithidcomponentofdevicewithid(Name alias, Table<DeviceswithidcomponentofdevicewithidRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Trustalo.TRUSTALO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DEVICESWITHIDCOMPONENTOFDEVICEWITHID_COMPOUNDCOMPONENTUNIQUE, Indexes.DEVICESWITHIDCOMPONENTOFDEVICEWITHID_DEVICESWITHIDCOMPONENTOFDEVICEWITHIDCOMPONENTFK, Indexes.DEVICESWITHIDCOMPONENTOFDEVICEWITHID_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DeviceswithidcomponentofdevicewithidRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_DEVICESWITHIDCOMPONENTOFDEVICEWITHID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DeviceswithidcomponentofdevicewithidRecord> getPrimaryKey() {
        return Keys.KEY_DEVICESWITHIDCOMPONENTOFDEVICEWITHID_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DeviceswithidcomponentofdevicewithidRecord>> getKeys() {
        return Arrays.<UniqueKey<DeviceswithidcomponentofdevicewithidRecord>>asList(Keys.KEY_DEVICESWITHIDCOMPONENTOFDEVICEWITHID_PRIMARY, Keys.KEY_DEVICESWITHIDCOMPONENTOFDEVICEWITHID_COMPOUNDCOMPONENTUNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DeviceswithidcomponentofdevicewithidRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DeviceswithidcomponentofdevicewithidRecord, ?>>asList(Keys.DEVICESWITHIDCOMPONENTOFDEVICEWITHIDCOMPOUNDFK, Keys.DEVICESWITHIDCOMPONENTOFDEVICEWITHIDCOMPONENTFK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Deviceswithidcomponentofdevicewithid as(String alias) {
        return new Deviceswithidcomponentofdevicewithid(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Deviceswithidcomponentofdevicewithid as(Name alias) {
        return new Deviceswithidcomponentofdevicewithid(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Deviceswithidcomponentofdevicewithid rename(String name) {
        return new Deviceswithidcomponentofdevicewithid(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Deviceswithidcomponentofdevicewithid rename(Name name) {
        return new Deviceswithidcomponentofdevicewithid(name, null);
    }
}
