/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Indexes;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Keys;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Trustalo;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records.DevicemodelsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Devicemodels extends TableImpl<DevicemodelsRecord> {

    private static final long serialVersionUID = 524599478;

    /**
     * The reference instance of <code>trustalo.devicemodels</code>
     */
    public static final Devicemodels DEVICEMODELS = new Devicemodels();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DevicemodelsRecord> getRecordType() {
        return DevicemodelsRecord.class;
    }

    /**
     * The column <code>trustalo.devicemodels.ID</code>.
     */
    public final TableField<DevicemodelsRecord, UInteger> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>trustalo.devicemodels.Vendor</code>.
     */
    public final TableField<DevicemodelsRecord, UShort> VENDOR = createField("Vendor", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED, this, "");

    /**
     * The column <code>trustalo.devicemodels.VendorModelNumber</code>.
     */
    public final TableField<DevicemodelsRecord, String> VENDORMODELNUMBER = createField("VendorModelNumber", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>trustalo.devicemodels.Category</code>.
     */
    public final TableField<DevicemodelsRecord, UByte> CATEGORY = createField("Category", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>trustalo.devicemodels.Description</code>.
     */
    public final TableField<DevicemodelsRecord, String> DESCRIPTION = createField("Description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>trustalo.devicemodels.DevicesWithoutID</code>.
     */
    public final TableField<DevicemodelsRecord, UShort> DEVICESWITHOUTID = createField("DevicesWithoutID", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>trustalo.devicemodels</code> table reference
     */
    public Devicemodels() {
        this(DSL.name("devicemodels"), null);
    }

    /**
     * Create an aliased <code>trustalo.devicemodels</code> table reference
     */
    public Devicemodels(String alias) {
        this(DSL.name(alias), DEVICEMODELS);
    }

    /**
     * Create an aliased <code>trustalo.devicemodels</code> table reference
     */
    public Devicemodels(Name alias) {
        this(alias, DEVICEMODELS);
    }

    private Devicemodels(Name alias, Table<DevicemodelsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Devicemodels(Name alias, Table<DevicemodelsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Trustalo.TRUSTALO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DEVICEMODELS_DEVICEMODELSCATEGORYFK, Indexes.DEVICEMODELS_DEVICEMODELSVENDORVENDORMODELNUMBERUNIQUE, Indexes.DEVICEMODELS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DevicemodelsRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_DEVICEMODELS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DevicemodelsRecord> getPrimaryKey() {
        return Keys.KEY_DEVICEMODELS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DevicemodelsRecord>> getKeys() {
        return Arrays.<UniqueKey<DevicemodelsRecord>>asList(Keys.KEY_DEVICEMODELS_PRIMARY, Keys.KEY_DEVICEMODELS_DEVICEMODELSVENDORVENDORMODELNUMBERUNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DevicemodelsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DevicemodelsRecord, ?>>asList(Keys.DEVICEMODELSVENDORFK, Keys.DEVICEMODELSCATEGORYFK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Devicemodels as(String alias) {
        return new Devicemodels(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Devicemodels as(Name alias) {
        return new Devicemodels(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Devicemodels rename(String name) {
        return new Devicemodels(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Devicemodels rename(Name name) {
        return new Devicemodels(name, null);
    }
}
