/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Indexes;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Keys;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Trustalo;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records.DeviceswithidRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Deviceswithid extends TableImpl<DeviceswithidRecord> {

    private static final long serialVersionUID = -223252920;

    /**
     * The reference instance of <code>trustalo.deviceswithid</code>
     */
    public static final Deviceswithid DEVICESWITHID = new Deviceswithid();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DeviceswithidRecord> getRecordType() {
        return DeviceswithidRecord.class;
    }

    /**
     * The column <code>trustalo.deviceswithid.ID</code>.
     */
    public final TableField<DeviceswithidRecord, UInteger> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>trustalo.deviceswithid.CategoryDeviceID</code>.
     */
    public final TableField<DeviceswithidRecord, UShort> CATEGORYDEVICEID = createField("CategoryDeviceID", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>trustalo.deviceswithid.DeviceModel</code>.
     */
    public final TableField<DeviceswithidRecord, UInteger> DEVICEMODEL = createField("DeviceModel", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>trustalo.deviceswithid.Category</code>.
     */
    public final TableField<DeviceswithidRecord, UByte> CATEGORY = createField("Category", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>trustalo.deviceswithid.Available</code>.
     */
    public final TableField<DeviceswithidRecord, Byte> AVAILABLE = createField("Available", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>trustalo.deviceswithid.CurrentState</code>.
     */
    public final TableField<DeviceswithidRecord, UByte> CURRENTSTATE = createField("CurrentState", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>trustalo.deviceswithid.LastUpdateWorker</code>.
     */
    public final TableField<DeviceswithidRecord, UInteger> LASTUPDATEWORKER = createField("LastUpdateWorker", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>trustalo.deviceswithid.Annotations</code>.
     */
    public final TableField<DeviceswithidRecord, String> ANNOTATIONS = createField("Annotations", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>trustalo.deviceswithid.LastUpdateDate</code>.
     */
    public final TableField<DeviceswithidRecord, Timestamp> LASTUPDATEDATE = createField("LastUpdateDate", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>trustalo.deviceswithid</code> table reference
     */
    public Deviceswithid() {
        this(DSL.name("deviceswithid"), null);
    }

    /**
     * Create an aliased <code>trustalo.deviceswithid</code> table reference
     */
    public Deviceswithid(String alias) {
        this(DSL.name(alias), DEVICESWITHID);
    }

    /**
     * Create an aliased <code>trustalo.deviceswithid</code> table reference
     */
    public Deviceswithid(Name alias) {
        this(alias, DEVICESWITHID);
    }

    private Deviceswithid(Name alias, Table<DeviceswithidRecord> aliased) {
        this(alias, aliased, null);
    }

    private Deviceswithid(Name alias, Table<DeviceswithidRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Trustalo.TRUSTALO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DEVICESWITHID_DEVICESRECORDEDWITHIDCATEGORYDEVICEIDDEVICEMODEL, Indexes.DEVICESWITHID_DEVICESRECORDEDWITHIDCATEGORYFK, Indexes.DEVICESWITHID_DEVICESRECORDEDWITHIDCURRENTSTATEFK, Indexes.DEVICESWITHID_DEVICESRECORDEDWITHIDDEVICEMODELFK, Indexes.DEVICESWITHID_DEVICESRECORDEDWITHIDWORKERFK_IDX, Indexes.DEVICESWITHID_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DeviceswithidRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_DEVICESWITHID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DeviceswithidRecord> getPrimaryKey() {
        return Keys.KEY_DEVICESWITHID_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DeviceswithidRecord>> getKeys() {
        return Arrays.<UniqueKey<DeviceswithidRecord>>asList(Keys.KEY_DEVICESWITHID_PRIMARY, Keys.KEY_DEVICESWITHID_DEVICESRECORDEDWITHIDCATEGORYDEVICEIDDEVICEMODEL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DeviceswithidRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DeviceswithidRecord, ?>>asList(Keys.DEVICESRECORDEDWITHIDDEVICEMODELFK, Keys.DEVICESRECORDEDWITHIDCATEGORYFK, Keys.DEVICESRECORDEDWITHIDCURRENTSTATEFK, Keys.DEVICESRECORDEDWITHIDWORKERFK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Deviceswithid as(String alias) {
        return new Deviceswithid(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Deviceswithid as(Name alias) {
        return new Deviceswithid(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Deviceswithid rename(String name) {
        return new Deviceswithid(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Deviceswithid rename(Name name) {
        return new Deviceswithid(name, null);
    }
}
