/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Indexes;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Keys;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Trustalo;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records.HddmodelsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Hddmodels extends TableImpl<HddmodelsRecord> {

    private static final long serialVersionUID = 1567610763;

    /**
     * The reference instance of <code>trustalo.hddmodels</code>
     */
    public static final Hddmodels HDDMODELS = new Hddmodels();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HddmodelsRecord> getRecordType() {
        return HddmodelsRecord.class;
    }

    /**
     * The column <code>trustalo.hddmodels.ID</code>.
     */
    public final TableField<HddmodelsRecord, UInteger> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>trustalo.hddmodels.Capacity</code>.
     */
    public final TableField<HddmodelsRecord, UShort> CAPACITY = createField("Capacity", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>trustalo.hddmodels.CapacityUnit</code>.
     */
    public final TableField<HddmodelsRecord, UByte> CAPACITYUNIT = createField("CapacityUnit", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>trustalo.hddmodels</code> table reference
     */
    public Hddmodels() {
        this(DSL.name("hddmodels"), null);
    }

    /**
     * Create an aliased <code>trustalo.hddmodels</code> table reference
     */
    public Hddmodels(String alias) {
        this(DSL.name(alias), HDDMODELS);
    }

    /**
     * Create an aliased <code>trustalo.hddmodels</code> table reference
     */
    public Hddmodels(Name alias) {
        this(alias, HDDMODELS);
    }

    private Hddmodels(Name alias, Table<HddmodelsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Hddmodels(Name alias, Table<HddmodelsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Trustalo.TRUSTALO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.HDDMODELS_HDDMODELSCAPACITYUNITFK, Indexes.HDDMODELS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<HddmodelsRecord> getPrimaryKey() {
        return Keys.KEY_HDDMODELS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<HddmodelsRecord>> getKeys() {
        return Arrays.<UniqueKey<HddmodelsRecord>>asList(Keys.KEY_HDDMODELS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<HddmodelsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<HddmodelsRecord, ?>>asList(Keys.HDDMODELSIDFK, Keys.HDDMODELSCAPACITYUNITFK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Hddmodels as(String alias) {
        return new Hddmodels(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Hddmodels as(Name alias) {
        return new Hddmodels(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Hddmodels rename(String name) {
        return new Hddmodels(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Hddmodels rename(Name name) {
        return new Hddmodels(name, null);
    }
}
