/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Indexes;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Keys;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Trustalo;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records.PeopleRecord;

import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class People extends TableImpl<PeopleRecord> {

    private static final long serialVersionUID = -1983876225;

    /**
     * The reference instance of <code>trustalo.people</code>
     */
    public static final People PEOPLE = new People();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PeopleRecord> getRecordType() {
        return PeopleRecord.class;
    }

    /**
     * The column <code>trustalo.people.ID</code>.
     */
    public final TableField<PeopleRecord, UInteger> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>trustalo.people.Category</code>.
     */
    public final TableField<PeopleRecord, UByte> CATEGORY = createField("Category", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>trustalo.people.Name</code>.
     */
    public final TableField<PeopleRecord, String> NAME = createField("Name", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>trustalo.people.BirthDate</code>.
     */
    public final TableField<PeopleRecord, Date> BIRTHDATE = createField("BirthDate", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>trustalo.people.BirthLocation</code>.
     */
    public final TableField<PeopleRecord, String> BIRTHLOCATION = createField("BirthLocation", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>trustalo.people.FiscalCode</code>.
     */
    public final TableField<PeopleRecord, String> FISCALCODE = createField("FiscalCode", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>trustalo.people.Annotations</code>.
     */
    public final TableField<PeopleRecord, String> ANNOTATIONS = createField("Annotations", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>trustalo.people</code> table reference
     */
    public People() {
        this(DSL.name("people"), null);
    }

    /**
     * Create an aliased <code>trustalo.people</code> table reference
     */
    public People(String alias) {
        this(DSL.name(alias), PEOPLE);
    }

    /**
     * Create an aliased <code>trustalo.people</code> table reference
     */
    public People(Name alias) {
        this(alias, PEOPLE);
    }

    private People(Name alias, Table<PeopleRecord> aliased) {
        this(alias, aliased, null);
    }

    private People(Name alias, Table<PeopleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Trustalo.TRUSTALO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PEOPLE_FISCALCODEUNIQUE, Indexes.PEOPLE_PEOPLECATEGORYFK, Indexes.PEOPLE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PeopleRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_PEOPLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PeopleRecord> getPrimaryKey() {
        return Keys.KEY_PEOPLE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PeopleRecord>> getKeys() {
        return Arrays.<UniqueKey<PeopleRecord>>asList(Keys.KEY_PEOPLE_PRIMARY, Keys.KEY_PEOPLE_FISCALCODEUNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PeopleRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PeopleRecord, ?>>asList(Keys.PEOPLECATEGORYFK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public People as(String alias) {
        return new People(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public People as(Name alias) {
        return new People(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public People rename(String name) {
        return new People(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public People rename(Name name) {
        return new People(name, null);
    }
}
