/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Indexes;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Keys;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Trustalo;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records.PersoncategoriesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Personcategories extends TableImpl<PersoncategoriesRecord> {

    private static final long serialVersionUID = 1316710688;

    /**
     * The reference instance of <code>trustalo.personcategories</code>
     */
    public static final Personcategories PERSONCATEGORIES = new Personcategories();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PersoncategoriesRecord> getRecordType() {
        return PersoncategoriesRecord.class;
    }

    /**
     * The column <code>trustalo.personcategories.ID</code>.
     */
    public final TableField<PersoncategoriesRecord, UByte> ID = createField("ID", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>trustalo.personcategories.Name</code>.
     */
    public final TableField<PersoncategoriesRecord, String> NAME = createField("Name", org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * Create a <code>trustalo.personcategories</code> table reference
     */
    public Personcategories() {
        this(DSL.name("personcategories"), null);
    }

    /**
     * Create an aliased <code>trustalo.personcategories</code> table reference
     */
    public Personcategories(String alias) {
        this(DSL.name(alias), PERSONCATEGORIES);
    }

    /**
     * Create an aliased <code>trustalo.personcategories</code> table reference
     */
    public Personcategories(Name alias) {
        this(alias, PERSONCATEGORIES);
    }

    private Personcategories(Name alias, Table<PersoncategoriesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Personcategories(Name alias, Table<PersoncategoriesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Trustalo.TRUSTALO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PERSONCATEGORIES_NAMEUNIQUE, Indexes.PERSONCATEGORIES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PersoncategoriesRecord, UByte> getIdentity() {
        return Keys.IDENTITY_PERSONCATEGORIES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PersoncategoriesRecord> getPrimaryKey() {
        return Keys.KEY_PERSONCATEGORIES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PersoncategoriesRecord>> getKeys() {
        return Arrays.<UniqueKey<PersoncategoriesRecord>>asList(Keys.KEY_PERSONCATEGORIES_PRIMARY, Keys.KEY_PERSONCATEGORIES_NAMEUNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Personcategories as(String alias) {
        return new Personcategories(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Personcategories as(Name alias) {
        return new Personcategories(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Personcategories rename(String name) {
        return new Personcategories(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Personcategories rename(Name name) {
        return new Personcategories(name, null);
    }
}
