/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Indexes;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Keys;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Trustalo;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records.RammodelsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rammodels extends TableImpl<RammodelsRecord> {

    private static final long serialVersionUID = 2144579119;

    /**
     * The reference instance of <code>trustalo.rammodels</code>
     */
    public static final Rammodels RAMMODELS = new Rammodels();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RammodelsRecord> getRecordType() {
        return RammodelsRecord.class;
    }

    /**
     * The column <code>trustalo.rammodels.DeviceModel</code>.
     */
    public final TableField<RammodelsRecord, UInteger> DEVICEMODEL = createField("DeviceModel", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>trustalo.rammodels.Capacity</code>.
     */
    public final TableField<RammodelsRecord, UShort> CAPACITY = createField("Capacity", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>trustalo.rammodels.CapacityUnit</code>.
     */
    public final TableField<RammodelsRecord, UByte> CAPACITYUNIT = createField("CapacityUnit", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>trustalo.rammodels</code> table reference
     */
    public Rammodels() {
        this(DSL.name("rammodels"), null);
    }

    /**
     * Create an aliased <code>trustalo.rammodels</code> table reference
     */
    public Rammodels(String alias) {
        this(DSL.name(alias), RAMMODELS);
    }

    /**
     * Create an aliased <code>trustalo.rammodels</code> table reference
     */
    public Rammodels(Name alias) {
        this(alias, RAMMODELS);
    }

    private Rammodels(Name alias, Table<RammodelsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Rammodels(Name alias, Table<RammodelsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Trustalo.TRUSTALO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.RAMMODELS_PRIMARY, Indexes.RAMMODELS_RAMMODELSCAPACITYUNITFK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RammodelsRecord> getPrimaryKey() {
        return Keys.KEY_RAMMODELS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RammodelsRecord>> getKeys() {
        return Arrays.<UniqueKey<RammodelsRecord>>asList(Keys.KEY_RAMMODELS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RammodelsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RammodelsRecord, ?>>asList(Keys.RAMMODELSDEVICEMODELFK, Keys.RAMMODELSCAPACITYUNITFK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Rammodels as(String alias) {
        return new Rammodels(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Rammodels as(Name alias) {
        return new Rammodels(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Rammodels rename(String name) {
        return new Rammodels(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Rammodels rename(Name name) {
        return new Rammodels(name, null);
    }
}
