/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Indexes;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Keys;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Trustalo;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records.RequeststatesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Requeststates extends TableImpl<RequeststatesRecord> {

    private static final long serialVersionUID = -1829135337;

    /**
     * The reference instance of <code>trustalo.requeststates</code>
     */
    public static final Requeststates REQUESTSTATES = new Requeststates();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RequeststatesRecord> getRecordType() {
        return RequeststatesRecord.class;
    }

    /**
     * The column <code>trustalo.requeststates.ID</code>.
     */
    public final TableField<RequeststatesRecord, UByte> ID = createField("ID", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>trustalo.requeststates.Name</code>.
     */
    public final TableField<RequeststatesRecord, String> NAME = createField("Name", org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>trustalo.requeststates.Description</code>.
     */
    public final TableField<RequeststatesRecord, String> DESCRIPTION = createField("Description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>trustalo.requeststates</code> table reference
     */
    public Requeststates() {
        this(DSL.name("requeststates"), null);
    }

    /**
     * Create an aliased <code>trustalo.requeststates</code> table reference
     */
    public Requeststates(String alias) {
        this(DSL.name(alias), REQUESTSTATES);
    }

    /**
     * Create an aliased <code>trustalo.requeststates</code> table reference
     */
    public Requeststates(Name alias) {
        this(alias, REQUESTSTATES);
    }

    private Requeststates(Name alias, Table<RequeststatesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Requeststates(Name alias, Table<RequeststatesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Trustalo.TRUSTALO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.REQUESTSTATES_NAME, Indexes.REQUESTSTATES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RequeststatesRecord, UByte> getIdentity() {
        return Keys.IDENTITY_REQUESTSTATES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RequeststatesRecord> getPrimaryKey() {
        return Keys.KEY_REQUESTSTATES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RequeststatesRecord>> getKeys() {
        return Arrays.<UniqueKey<RequeststatesRecord>>asList(Keys.KEY_REQUESTSTATES_PRIMARY, Keys.KEY_REQUESTSTATES_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Requeststates as(String alias) {
        return new Requeststates(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Requeststates as(Name alias) {
        return new Requeststates(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Requeststates rename(String name) {
        return new Requeststates(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Requeststates rename(Name name) {
        return new Requeststates(name, null);
    }
}
