/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Indexes;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Keys;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Trustalo;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records.ScreentecnologiesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Screentecnologies extends TableImpl<ScreentecnologiesRecord> {

    private static final long serialVersionUID = -543692380;

    /**
     * The reference instance of <code>trustalo.screentecnologies</code>
     */
    public static final Screentecnologies SCREENTECNOLOGIES = new Screentecnologies();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScreentecnologiesRecord> getRecordType() {
        return ScreentecnologiesRecord.class;
    }

    /**
     * The column <code>trustalo.screentecnologies.ID</code>.
     */
    public final TableField<ScreentecnologiesRecord, UByte> ID = createField("ID", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>trustalo.screentecnologies.Name</code>.
     */
    public final TableField<ScreentecnologiesRecord, String> NAME = createField("Name", org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * Create a <code>trustalo.screentecnologies</code> table reference
     */
    public Screentecnologies() {
        this(DSL.name("screentecnologies"), null);
    }

    /**
     * Create an aliased <code>trustalo.screentecnologies</code> table reference
     */
    public Screentecnologies(String alias) {
        this(DSL.name(alias), SCREENTECNOLOGIES);
    }

    /**
     * Create an aliased <code>trustalo.screentecnologies</code> table reference
     */
    public Screentecnologies(Name alias) {
        this(alias, SCREENTECNOLOGIES);
    }

    private Screentecnologies(Name alias, Table<ScreentecnologiesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Screentecnologies(Name alias, Table<ScreentecnologiesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Trustalo.TRUSTALO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SCREENTECNOLOGIES_NAME, Indexes.SCREENTECNOLOGIES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ScreentecnologiesRecord, UByte> getIdentity() {
        return Keys.IDENTITY_SCREENTECNOLOGIES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ScreentecnologiesRecord> getPrimaryKey() {
        return Keys.KEY_SCREENTECNOLOGIES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ScreentecnologiesRecord>> getKeys() {
        return Arrays.<UniqueKey<ScreentecnologiesRecord>>asList(Keys.KEY_SCREENTECNOLOGIES_PRIMARY, Keys.KEY_SCREENTECNOLOGIES_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Screentecnologies as(String alias) {
        return new Screentecnologies(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Screentecnologies as(Name alias) {
        return new Screentecnologies(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Screentecnologies rename(String name) {
        return new Screentecnologies(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Screentecnologies rename(Name name) {
        return new Screentecnologies(name, null);
    }
}
