/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Indexes;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Keys;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Trustalo;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records.ScreenmodelsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Screenmodels extends TableImpl<ScreenmodelsRecord> {

    private static final long serialVersionUID = 842239343;

    /**
     * The reference instance of <code>trustalo.screenmodels</code>
     */
    public static final Screenmodels SCREENMODELS = new Screenmodels();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScreenmodelsRecord> getRecordType() {
        return ScreenmodelsRecord.class;
    }

    /**
     * The column <code>trustalo.screenmodels.DeviceModel</code>.
     */
    public final TableField<ScreenmodelsRecord, UInteger> DEVICEMODEL = createField("DeviceModel", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>trustalo.screenmodels.MaximumResolution</code>.
     */
    public final TableField<ScreenmodelsRecord, UByte> MAXIMUMRESOLUTION = createField("MaximumResolution", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>trustalo.screenmodels.Tecnology</code>.
     */
    public final TableField<ScreenmodelsRecord, UByte> TECNOLOGY = createField("Tecnology", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>trustalo.screenmodels.WithFrame</code>.
     */
    public final TableField<ScreenmodelsRecord, Byte> WITHFRAME = createField("WithFrame", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>trustalo.screenmodels.Color</code>.
     */
    public final TableField<ScreenmodelsRecord, UByte> COLOR = createField("Color", org.jooq.impl.SQLDataType.TINYINTUNSIGNED, this, "");

    /**
     * The column <code>trustalo.screenmodels.HasVGASocket</code>.
     */
    public final TableField<ScreenmodelsRecord, Byte> HASVGASOCKET = createField("HasVGASocket", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>trustalo.screenmodels.HasDVISocket</code>.
     */
    public final TableField<ScreenmodelsRecord, Byte> HASDVISOCKET = createField("HasDVISocket", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>trustalo.screenmodels.HasAudioSpeakers</code>.
     */
    public final TableField<ScreenmodelsRecord, Byte> HASAUDIOSPEAKERS = createField("HasAudioSpeakers", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * Create a <code>trustalo.screenmodels</code> table reference
     */
    public Screenmodels() {
        this(DSL.name("screenmodels"), null);
    }

    /**
     * Create an aliased <code>trustalo.screenmodels</code> table reference
     */
    public Screenmodels(String alias) {
        this(DSL.name(alias), SCREENMODELS);
    }

    /**
     * Create an aliased <code>trustalo.screenmodels</code> table reference
     */
    public Screenmodels(Name alias) {
        this(alias, SCREENMODELS);
    }

    private Screenmodels(Name alias, Table<ScreenmodelsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Screenmodels(Name alias, Table<ScreenmodelsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Trustalo.TRUSTALO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SCREENMODELS_PRIMARY, Indexes.SCREENMODELS_SCREENMODELSCOLORFK, Indexes.SCREENMODELS_SCREENMODELSMAXIMUMRESOLUTIONFK, Indexes.SCREENMODELS_SCREENMODELSTECNOLOGYFK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ScreenmodelsRecord> getPrimaryKey() {
        return Keys.KEY_SCREENMODELS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ScreenmodelsRecord>> getKeys() {
        return Arrays.<UniqueKey<ScreenmodelsRecord>>asList(Keys.KEY_SCREENMODELS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ScreenmodelsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ScreenmodelsRecord, ?>>asList(Keys.SCREENMODELSDEVICEMODELFK, Keys.SCREENMODELSMAXIMUMRESOLUTIONFK, Keys.SCREENMODELSTECNOLOGYFK, Keys.SCREENMODELSCOLORFK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Screenmodels as(String alias) {
        return new Screenmodels(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Screenmodels as(Name alias) {
        return new Screenmodels(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Screenmodels rename(String name) {
        return new Screenmodels(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Screenmodels rename(Name name) {
        return new Screenmodels(name, null);
    }
}
