/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Indexes;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Keys;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Trustalo;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records.ScreenresolutionsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Screenresolutions extends TableImpl<ScreenresolutionsRecord> {

    private static final long serialVersionUID = -1539747168;

    /**
     * The reference instance of <code>trustalo.screenresolutions</code>
     */
    public static final Screenresolutions SCREENRESOLUTIONS = new Screenresolutions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScreenresolutionsRecord> getRecordType() {
        return ScreenresolutionsRecord.class;
    }

    /**
     * The column <code>trustalo.screenresolutions.ID</code>.
     */
    public final TableField<ScreenresolutionsRecord, UByte> ID = createField("ID", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>trustalo.screenresolutions.Width</code>.
     */
    public final TableField<ScreenresolutionsRecord, UShort> WIDTH = createField("Width", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>trustalo.screenresolutions.Height</code>.
     */
    public final TableField<ScreenresolutionsRecord, UShort> HEIGHT = createField("Height", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>trustalo.screenresolutions.AspectRatio</code>.
     */
    public final TableField<ScreenresolutionsRecord, UByte> ASPECTRATIO = createField("AspectRatio", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>trustalo.screenresolutions</code> table reference
     */
    public Screenresolutions() {
        this(DSL.name("screenresolutions"), null);
    }

    /**
     * Create an aliased <code>trustalo.screenresolutions</code> table reference
     */
    public Screenresolutions(String alias) {
        this(DSL.name(alias), SCREENRESOLUTIONS);
    }

    /**
     * Create an aliased <code>trustalo.screenresolutions</code> table reference
     */
    public Screenresolutions(Name alias) {
        this(alias, SCREENRESOLUTIONS);
    }

    private Screenresolutions(Name alias, Table<ScreenresolutionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Screenresolutions(Name alias, Table<ScreenresolutionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Trustalo.TRUSTALO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SCREENRESOLUTIONS_PRIMARY, Indexes.SCREENRESOLUTIONS_SCREENRESOLUTIONSASPECTRATIOFK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ScreenresolutionsRecord, UByte> getIdentity() {
        return Keys.IDENTITY_SCREENRESOLUTIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ScreenresolutionsRecord> getPrimaryKey() {
        return Keys.KEY_SCREENRESOLUTIONS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ScreenresolutionsRecord>> getKeys() {
        return Arrays.<UniqueKey<ScreenresolutionsRecord>>asList(Keys.KEY_SCREENRESOLUTIONS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ScreenresolutionsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ScreenresolutionsRecord, ?>>asList(Keys.SCREENRESOLUTIONSASPECTRATIOFK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Screenresolutions as(String alias) {
        return new Screenresolutions(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Screenresolutions as(Name alias) {
        return new Screenresolutions(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Screenresolutions rename(String name) {
        return new Screenresolutions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Screenresolutions rename(Name name) {
        return new Screenresolutions(name, null);
    }
}
