/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Indexes;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Keys;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Trustalo;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records.VendorsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Vendors extends TableImpl<VendorsRecord> {

    private static final long serialVersionUID = -1125290889;

    /**
     * The reference instance of <code>trustalo.vendors</code>
     */
    public static final Vendors VENDORS = new Vendors();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VendorsRecord> getRecordType() {
        return VendorsRecord.class;
    }

    /**
     * The column <code>trustalo.vendors.ID</code>.
     */
    public final TableField<VendorsRecord, UShort> ID = createField("ID", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>trustalo.vendors.Name</code>.
     */
    public final TableField<VendorsRecord, String> NAME = createField("Name", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * Create a <code>trustalo.vendors</code> table reference
     */
    public Vendors() {
        this(DSL.name("vendors"), null);
    }

    /**
     * Create an aliased <code>trustalo.vendors</code> table reference
     */
    public Vendors(String alias) {
        this(DSL.name(alias), VENDORS);
    }

    /**
     * Create an aliased <code>trustalo.vendors</code> table reference
     */
    public Vendors(Name alias) {
        this(alias, VENDORS);
    }

    private Vendors(Name alias, Table<VendorsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Vendors(Name alias, Table<VendorsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Trustalo.TRUSTALO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.VENDORS_NAME, Indexes.VENDORS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<VendorsRecord, UShort> getIdentity() {
        return Keys.IDENTITY_VENDORS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<VendorsRecord> getPrimaryKey() {
        return Keys.KEY_VENDORS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<VendorsRecord>> getKeys() {
        return Arrays.<UniqueKey<VendorsRecord>>asList(Keys.KEY_VENDORS_PRIMARY, Keys.KEY_VENDORS_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Vendors as(String alias) {
        return new Vendors(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Vendors as(Name alias) {
        return new Vendors(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Vendors rename(String name) {
        return new Vendors(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Vendors rename(Name name) {
        return new Vendors(name, null);
    }
}
