/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Indexes;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Keys;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.Trustalo;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records.WorkercategoriesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Workercategories extends TableImpl<WorkercategoriesRecord> {

    private static final long serialVersionUID = -1147193506;

    /**
     * The reference instance of <code>trustalo.workercategories</code>
     */
    public static final Workercategories WORKERCATEGORIES = new Workercategories();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WorkercategoriesRecord> getRecordType() {
        return WorkercategoriesRecord.class;
    }

    /**
     * The column <code>trustalo.workercategories.ID</code>.
     */
    public final TableField<WorkercategoriesRecord, UByte> ID = createField("ID", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>trustalo.workercategories.Name</code>.
     */
    public final TableField<WorkercategoriesRecord, String> NAME = createField("Name", org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * Create a <code>trustalo.workercategories</code> table reference
     */
    public Workercategories() {
        this(DSL.name("workercategories"), null);
    }

    /**
     * Create an aliased <code>trustalo.workercategories</code> table reference
     */
    public Workercategories(String alias) {
        this(DSL.name(alias), WORKERCATEGORIES);
    }

    /**
     * Create an aliased <code>trustalo.workercategories</code> table reference
     */
    public Workercategories(Name alias) {
        this(alias, WORKERCATEGORIES);
    }

    private Workercategories(Name alias, Table<WorkercategoriesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Workercategories(Name alias, Table<WorkercategoriesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Trustalo.TRUSTALO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.WORKERCATEGORIES_NAME, Indexes.WORKERCATEGORIES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<WorkercategoriesRecord, UByte> getIdentity() {
        return Keys.IDENTITY_WORKERCATEGORIES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<WorkercategoriesRecord> getPrimaryKey() {
        return Keys.KEY_WORKERCATEGORIES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<WorkercategoriesRecord>> getKeys() {
        return Arrays.<UniqueKey<WorkercategoriesRecord>>asList(Keys.KEY_WORKERCATEGORIES_PRIMARY, Keys.KEY_WORKERCATEGORIES_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Workercategories as(String alias) {
        return new Workercategories(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Workercategories as(Name alias) {
        return new Workercategories(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Workercategories rename(String name) {
        return new Workercategories(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Workercategories rename(Name name) {
        return new Workercategories(name, null);
    }
}
