package controller.api;

import model.ShopModel;

/**
 * Interface representing the controller for menu-related actions.
 */
public interface ControllerMenu {
    /**
     * Handles an event generated by the user interface.
     *
     * @param e the event to be handled
     */
    void handleEvent(State e);

    /**
     * Selects the visual skin of the player.
     *
     * @param frame1 the first image representing the selected skin
     * @param frame2 the second image representing the selected skin
     */
    default void selectSkin(final String frame1, final String frame2) {
        // default implementation
    }

    /**
     * Returns the shop model containing purchased and available skins.
     *
     * @return the shop model
     */
    ShopModel getShopModel();

}
