package moves.damagingmove.special;

import battle_arena.BattleArena;
import pokemon.Pokemon;
import types.Dragon;

public class DragonPulse extends SpecialDamagingMove{

    public DragonPulse() {
        super(  "Dragon Pulse",                                                                                //name
                "The target is attacked with a shock wave generated by the user's gaping mouth.",              //description              
                85,                                                                                            //base power
                new Dragon(),                                                                                   //type
                1,                                                                                             //accuracy
                critRange1,                                                                                    //crit range 
                10,                                                                                            //PP
                0);                                                                                            //Priority
    }

    @Override
    public void sideEffect(Pokemon user, Pokemon target, BattleArena battleArena) {
    }
 
}
