package it.unibo.geometrybash.commons.pattern.observerpattern.viewobserverpattern;

import it.unibo.geometrybash.commons.pattern.observerpattern.Event;

/**
 * A class that represent an event generated by the view that is listened by a
 * view observer.
 *
 * <p>
 * The event type is represented using {@link ViewEventType}.
 *
 * @see ViewObserver
 * @see Event
 */
public final class ViewEvent implements Event {

    /**
     * The type of event generated.
     *
     * @see ViewEventType
     */
    private final ViewEventType type;

    private ViewEvent(final ViewEventType type) {
        this.type = type;
    }

    /**
     * Creates a ViewEvent with the given type.
     *
     * @param type the event type
     * @return a new ViewEvent instance
     */
    public static ViewEvent createEvent(final ViewEventType type) {
        return new ViewEvent(type);

    }

    /**
     * A method that returns the type of the event.
     *
     * @return the {@link ViewEventType} of this instance.
     */
    public ViewEventType getType() {
        return type;
    }

    /**
     * A method that returns the name of the event.
     *
     * @return the name of the type represented by this event.
     */
    @Override
    public String getEventName() {
        return type.getCommand();
    }
}
