package pokemon;

public class PlayerPokemonAviliable {
    
    public static final Pokemon[] PLAYERAVAILABLE = new Pokemon[]{   new Bulbasaur(50), new Ivysaur(50), new Venusaur(50), 
                                                                     new Charmander(50), new Charmeleon(50), new Charizard(50),
                                                                     new Squirtle(50), new Wartortle(50), new Blastoise(50), 
                                                                     new Rattata(50), new Raticate(50), new Pikachu(50),
                                                                     new Raichu(50), new Caterpie(50), new Metapod(50), 
                                                                     new Butterfree(50), new Weedle(50), new Kakuna(50),
                                                                     new Beedrill(50), new Pidgey(50), new Pidgeotto(50), 
                                                                     new Pidgeot(50), new Bellsprout(50), new Weepinbell(50),
                                                                     new Victreebel(50), new Oddish(50), new Gloom(50), 
                                                                     new Vileplume(50), new Eevee(50), new Vaporeon(50),
                                                                     new Jolteon(50), new Flareon(50), new Spearow(50), 
                                                                     new Fearow(50), new Snorlax(50), new Growlithe(50),
                                                                     new Arcanine(50), new Magikarp(50), new Gyarados(50), 
                                                                     new Poliwag(50), new Poliwhirl(50), new Poliwrath(50),
                                                                     new Kabuto(50), new Kabutops(50), new NidoranM(50), 
                                                                     new NidoranF(50), new Nidorino(50), new Nidorina(50),
                                                                     new Nidoking(50), new Nidoqueen(50), new Clefairy(50), 
                                                                     new Clefable(50), new Vulpix(50), new Ninetales(50),
                                                                     new Diglett(50), new Dugtrio(50), new Meowth(50), 
                                                                     new Persian(50), new Mankey(50), new Persian(50),
                                                                     new Abra(50), new Kadabra(50), new Tentacool(50), 
                                                                     new Tentacruel(50), new Magnemite(50), new Magneton(50),
                                                                     new Grimer(50), new Shellder(50), new Cloyster(50), 
                                                                     new Drowzee(50), new Exeggcute(50), new Exeggutor(50),
                                                                     new Cubone(50), new Marowak(50), new Koffing(50),
                                                                     new Weezing(50), new Kangaskhan(50), new MrMime(50),
                                                                     new Jynx(50), new Chikorita(50), new Bayleef(50), 
                                                                     new Meganium(50), new Cyndaquil(50), new Typhlosion(50),
                                                                     new Totodile(50), new Croconaw(50), new Feraligatr(50),
                                                                     new Sentret(50), new Furret(50), new Hoothoot(50), 
                                                                     new Noctowl(50), new Spinarak(50), new Chinchou(50),
                                                                     new Natu(50), new Xatu(50), new Mareep(50), 
                                                                     new Flaaffy(50), new Hoppip(50), new Skiploom(50),
                                                                     new Jumpluff(50), new Sunkern(50), new Yanma(50), 
                                                                     new Espeon(50), new Umbreon(50), new Girafarig(50),
                                                                     new Pineco(50), new Forretress(50), new Gligar(50), 
                                                                     new Qwilfish(50), new Heracross(50), new Sneasel(50),
                                                                     new Teddiursa(50), new Ursaring(50), new Slugma(50), 
                                                                     new Magcargo(50), new Swinub(50), new Piloswine(50),
                                                                     new Corsola(50), new Octillery(50), new Delibird(50), 
                                                                     new Phanpy(50), new Donphan(50), new Stantler(50),
                                                                     new Treecko(50), new Grovyle(50), new Sceptile(50), 
                                                                     new Torchic(50), new Combusken(50), new Blaziken(50),
                                                                     new Mudkip(50), new Marshtomp(50), new Swampert(50), 
                                                                     new Poochyena(50), new Zigzagoon(50), new Linoone(50),
                                                                     new Wurmple(50), new Cascoon(50), new Silcoon(50), 
                                                                     new Beautifly(50), new Dustox(50), new Lotad(50),
                                                                     new Lombre(50), new Seedot(50), new Nuzleaf(50), 
                                                                     new Taillow(50), new Swellow(50), new Ralts(50),
                                                                     new Kirlia(50), new Gardevoir(50), new Masquerain(50),
                                                                     new Vigoroth(50), new Nincada(50), new Whismur(50),
                                                                     new Loudred(50), new Exploud(50), new Makuhita(50),
                                                                     new Hariyama(50), new Nosepass(50), new Mawile(50),
                                                                     new Aron(50), new Meditite(50), new Electrike(50), 
                                                                     new Manectric(50), new Plusle(50), new Minun(50),
                                                                     new Volbeat(50), new Illumise(50), new Roselia(50),
                                                                     new Gulpin(50), new Wailmer(50), new Numel(50), 
                                                                     new Camerupt(50), new Torkoal(50), new Spoink(50),
                                                                     new Spinda(50), new Trapinch(50), new Vibrava(50), 
                                                                     new Flygon(50), new Cacnea(50), new Swablu(50),
                                                                     new Zangoose(50), new Barboach(50), new Whiscash(50), 
                                                                     new Baltoy(50), new Claydol(50), new Feebas(50),
                                                                     new Milotic(50), new Castform(50), new Kecleon(50), 
                                                                     new Shuppet(50), new Duskull(50), new Tropius(50),
                                                                     new Snorunt(50), new Spheal(50), new Sealeo(50), 
                                                                     new Clamperl(50), new Bagon(50), new Beldum(50),
                                                                     new Corsola(50), new Octillery(50), new Delibird(50), 
                                                                     new Phanpy(50), new Donphan(50), new Stantler(50),
                                                                     new Treecko(50), new Grovyle(50), new Sceptile(50), 
                                                                     new Torchic(50), new Combusken(50), new Blaziken(50),
                                                                     new Mudkip(50), new Marshtomp(50), new Swampert(50), 
                                                                     new Poochyena(50), new Zigzagoon(50), new Linoone(50),
                                                                     new Wurmple(50), new Cascoon(50), new Silcoon(50), 
                                                                     new Beautifly(50), new Dustox(50), new Lotad(50),
                                                                     new Lombre(50), new Seedot(50), new Nuzleaf(50), 
                                                                     new Taillow(50), new Swellow(50), new Ralts(50),};

    public PlayerPokemonAviliable() {
        // TODO Auto-generated constructor stub
    }

}
