package View.cardlayout;

import java.awt.event.ActionListener;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

public class ViewScontrinoBackup extends JPanel {
	private static final int index = 4;
	private JTextField textField;
	
    public ViewScontrinoBackup()  {
    	initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	this.setLayout(null);
		this.setSize(800, 800);
	    this.setVisible(true);
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblcas = new javax.swing.JLabel();
        lbld = new javax.swing.JLabel();
        lbld.setText("NumScontrino");
        lblpay = new javax.swing.JLabel();
        lbltot = new javax.swing.JLabel();
        lblh = new javax.swing.JLabel();
        lblh.setText("Date and Hour");
        jLabel9 = new javax.swing.JLabel();
        

       
        setPreferredSize(new java.awt.Dimension(670, 550));
       

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 570));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Scontrino");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(240, 0, 170, 40);
        JLabel lblNome = new JLabel("Numero Tavolo");
		lblNome.setBounds(22, 11, 46, 14);
		jPanel1.add(lblNome);
		JTextField textField = new JTextField();
		textField.setBounds(95, 8, 86, 20);
		jPanel1.add(textField);
		textField.setColumns(10);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 90, 590, 120);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("indietro");
       
        jPanel1.add(jButton1);
        jButton1.setBounds(60, 320, 130, 50);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("stampare");
        
        jPanel1.add(jButton3);
        jButton3.setBounds(60, 250, 130, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("cash :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(320, 330, 90, 70);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("resto :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(320, 410, 90, 70);

        lblcas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblcas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcas.setText("xx");
        jPanel1.add(lblcas);
        lblcas.setBounds(430, 340, 140, 50);

        lbld.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(lbld);
        lbld.setBounds(10, 40, 270, 30);

        lblpay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblpay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpay.setText("xx");
        lblpay.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblpay);
        lblpay.setBounds(430, 420, 140, 50);

        lbltot.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbltot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltot.setText("xx");
        jPanel1.add(lbltot);
        lbltot.setBounds(430, 250, 140, 60);

        lblh.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(lblh);
        lblh.setBounds(430, 10, 170, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Totale :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(320, 250, 110, 70);

        this.add(jPanel1);
        jPanel1.setBounds(10, 0, 620, 500);

    }// </editor-fold>//GEN-END:initComponents

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblcas;
    private javax.swing.JLabel lbld;
    private javax.swing.JLabel lblh;
    private javax.swing.JLabel lblpay;
    private javax.swing.JLabel lbltot;
	
    // End of variables declaration//GEN-END:variables
    public void addButtonListener(ActionListener listener)
	{
		this.jButton3.addActionListener(listener);
	}
    public String getName() {
        return this.textField.getText().trim();
    }
    public static int getIndex()
    {
    	return index;
    }
}

