package controller.gui.pause;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

public interface GUIPause1Controller {

    /**
     * The handler for the click event generated by the 'continue' button.
     * go back to the game.
     * 
     * @throws IOException
     *              if the name of the fxml is wrong
     */
    void continueBtnOnClickHandler() throws IOException;

    /**
     * The handler for the click event generated by the 'tutorial' button.
     * show a textArea with the rules and command.
     * 
     * @throws IOException
     *              if the name of the fxml is wrong
     */
    void tutorialBtnOnClickHandler() throws IOException;

    /**
     * The handler for the click event generated by the 'menu' button.
     * go back to the main menu, without saving the current game.
     * 
     * @throws IOException
     *              if the name of the fxml is wrong
     */
    void menuBtnOnClickHandler() throws IOException;

    /**
     * 
     * @throws IOException
     * 
     * close the textual tutorial
     */
    void closeBtnOnClickHandler() throws IOException;

    /**
     * The handler for the click event generated by the 'retry' button.
     * show the retryPanel with its choises.
     * 
     * @throws IOException
     *              if the name of the fxml is wrong
     */
    void retryBtnOnClickHandler() throws IOException;

    /**
     * 
     * @throws IOException
     * 
     * close the retryPane
     */
    void noBtnOnClickHandler() throws IOException;

    /**
     * 
     * @throws IOException
     * 
     * load a new game, without saving the current one.
     */
    void yesBtnOnClickHandler() throws IOException;

    /**
     * 
     * @param location
     * @param resources
     * 
     * hide the tutorial textArea and the retryPanel.
     */
    void initialize(URL location, ResourceBundle resources);
}
