package it.unibo.turbochess.model.replay.impl;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import it.unibo.turbochess.model.chessboard.board.api.BoardObserver;
import it.unibo.turbochess.model.entity.api.Entity;
import it.unibo.turbochess.model.entity.impl.PlayerColor;
import it.unibo.turbochess.model.point2d.Point2D;
import it.unibo.turbochess.model.replay.api.GameEvent;
import it.unibo.turbochess.model.replay.api.GameHistory;
import it.unibo.turbochess.model.score.api.ScoreManager;

import java.util.function.Supplier;
import java.util.List;

/**
 * Records game events into a GameHistory.
 * Filters out redundant events generated by the internal logic of ChessBoardImpl.
 */
public final class GameHistoryRecorder implements BoardObserver {

    private final GameHistory history;
    private final Supplier<Integer> turnSupplier;
    private final Supplier<ScoreManager> scoreSupplier;

    /**
     * @param turnSupplier a supplier that provides the current turn number.
     * @param scoreSupplier a supplier that provides the score manager.
     */
    public GameHistoryRecorder(final Supplier<Integer> turnSupplier, final Supplier<ScoreManager> scoreSupplier) {
        this.history = new GameHistoryImpl();
        this.turnSupplier = turnSupplier;
        this.scoreSupplier = scoreSupplier;
    }

    /**
     * @return the recorded history.
     */
    @SuppressFBWarnings(
        value = "EI_EXPOSE_REP",
        justification = "The history is exposed to allow replay functionality to access the recorded events."
    )
    public GameHistory getHistory() {
        return history;
    }

    @Override
    public void onEntityAdded(final Point2D pos, final Entity entity) {
        if (history.getLastEvent() instanceof DespawnEvent despawn && despawn.position().equals(pos)) {
            final List<GameEvent> events = history.getEvents();
            if (events.size() >= 2) {
                final GameEvent potentialMove = events.get(events.size() - 2);
                if (potentialMove instanceof MoveEvent move 
                        && move.to().equals(pos)
                        && move.entityName().equals(despawn.entity().getName())
                        && move.entityColor() == despawn.entity().getPlayerColor()) {

                    history.removeLastEvent();
                    history.removeLastEvent();
                    final MoveEvent mergedMove = new MoveEvent(
                        move.turn(),
                        move.entityName(),
                        move.entityColor(),
                        move.from(),
                        move.to(),
                        move.capturedEntity(),
                        entity,
                        despawn.entity(),
                        scoreSupplier.get().getScore(PlayerColor.WHITE),
                        scoreSupplier.get().getScore(PlayerColor.BLACK)
                    );
                    history.addEvent(mergedMove);
                    return;
                }
            }
        }

        final var spawnEvent = new SpawnEvent(turnSupplier.get(), entity, pos, 
            scoreSupplier.get().getScore(PlayerColor.WHITE), 
            scoreSupplier.get().getScore(PlayerColor.BLACK));
        history.addEvent(spawnEvent);
    }

    @Override
    public void onEntityRemoved(final Point2D pos, final Entity entity) {
        final var despawnEvent = new DespawnEvent(turnSupplier.get(), entity, pos, 
            scoreSupplier.get().getScore(PlayerColor.WHITE), 
            scoreSupplier.get().getScore(PlayerColor.BLACK));
        history.addEvent(despawnEvent);
    }

    @Override
    public void onEntityMoved(final Point2D from, final Point2D to, final Entity entity) {
        final String entityName = entity.getName();
        final var entityColor = entity.getPlayerColor();
        Entity capturedEntity = null;

        if (history.getLastEvent() instanceof SpawnEvent spawn && spawn.position().equals(to)) {
            history.removeLastEvent();
        }

        if (history.getLastEvent() instanceof DespawnEvent despawn && despawn.position().equals(from)) {
             history.removeLastEvent();
        }

        if (history.getLastEvent() instanceof DespawnEvent despawn && despawn.position().equals(to)) {
             capturedEntity = despawn.entity();
             history.removeLastEvent();
        }

        if (history.getLastEvent() instanceof DespawnEvent despawn && despawn.position().equals(from)) {
             history.removeLastEvent();
        }

        final var moveEvent = new MoveEvent(turnSupplier.get(), entityName, entityColor, from, to, capturedEntity, 
            scoreSupplier.get().getScore(PlayerColor.WHITE), 
            scoreSupplier.get().getScore(PlayerColor.BLACK));
        history.addEvent(moveEvent);
    }

}
