package controller.gui.exit;

import java.io.IOException;

public interface GUIExitController {

    /**
     * The handler for the click event generated by the 'no' button.
     * go back to the main menu.
     * 
     * @throws IOException
     *              if the name of the fxml is wrong
     */
    void noBtnOnClickHandler() throws IOException;

    /**
     * The handler for the click event generated by the 'yes' button.
     * The application will close.
     * 
     * @throws IOException
     *              if the name of the fxml is wrong
     */
    void yesBtnOnClickHandler() throws IOException;

}
