/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Aspectratios;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Casemodels;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Colors;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Contactcategories;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Contacts;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Devicecategoryallowedcomponents;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Devicemodels;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Devicerequestdetails;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Devicerequests;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Devicerequestsdevicemodels;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Devicerequestsdeviceswithid;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Devicestates;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Deviceswithid;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Deviceswithidcomponentofdevicewithid;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Deviceswithoutidcomponentofdevicewithid;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Digitalinformationunits;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Hddmodels;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.People;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Personcategories;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Printermodels;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Printertecnologies;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Rammodels;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Requeststates;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Screenmodels;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Screenresolutions;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Screentecnologies;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Trashwaredevicecategories;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Vendors;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Workercategories;
import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Workers;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in trustalo
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>trustalo.aspectratios</code>.
     */
    public static final Aspectratios ASPECTRATIOS = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Aspectratios.ASPECTRATIOS;

    /**
     * The table <code>trustalo.casemodels</code>.
     */
    public static final Casemodels CASEMODELS = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Casemodels.CASEMODELS;

    /**
     * The table <code>trustalo.colors</code>.
     */
    public static final Colors COLORS = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Colors.COLORS;

    /**
     * The table <code>trustalo.contactcategories</code>.
     */
    public static final Contactcategories CONTACTCATEGORIES = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Contactcategories.CONTACTCATEGORIES;

    /**
     * The table <code>trustalo.contacts</code>.
     */
    public static final Contacts CONTACTS = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Contacts.CONTACTS;

    /**
     * The table <code>trustalo.devicecategoryallowedcomponents</code>.
     */
    public static final Devicecategoryallowedcomponents DEVICECATEGORYALLOWEDCOMPONENTS = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Devicecategoryallowedcomponents.DEVICECATEGORYALLOWEDCOMPONENTS;

    /**
     * The table <code>trustalo.devicemodels</code>.
     */
    public static final Devicemodels DEVICEMODELS = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Devicemodels.DEVICEMODELS;

    /**
     * The table <code>trustalo.devicerequestdetails</code>.
     */
    public static final Devicerequestdetails DEVICEREQUESTDETAILS = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Devicerequestdetails.DEVICEREQUESTDETAILS;

    /**
     * The table <code>trustalo.devicerequests</code>.
     */
    public static final Devicerequests DEVICEREQUESTS = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Devicerequests.DEVICEREQUESTS;

    /**
     * The table <code>trustalo.devicerequestsdevicemodels</code>.
     */
    public static final Devicerequestsdevicemodels DEVICEREQUESTSDEVICEMODELS = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Devicerequestsdevicemodels.DEVICEREQUESTSDEVICEMODELS;

    /**
     * The table <code>trustalo.devicerequestsdeviceswithid</code>.
     */
    public static final Devicerequestsdeviceswithid DEVICEREQUESTSDEVICESWITHID = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Devicerequestsdeviceswithid.DEVICEREQUESTSDEVICESWITHID;

    /**
     * The table <code>trustalo.devicestates</code>.
     */
    public static final Devicestates DEVICESTATES = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Devicestates.DEVICESTATES;

    /**
     * The table <code>trustalo.deviceswithid</code>.
     */
    public static final Deviceswithid DEVICESWITHID = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Deviceswithid.DEVICESWITHID;

    /**
     * The table <code>trustalo.deviceswithidcomponentofdevicewithid</code>.
     */
    public static final Deviceswithidcomponentofdevicewithid DEVICESWITHIDCOMPONENTOFDEVICEWITHID = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Deviceswithidcomponentofdevicewithid.DEVICESWITHIDCOMPONENTOFDEVICEWITHID;

    /**
     * The table <code>trustalo.deviceswithoutidcomponentofdevicewithid</code>.
     */
    public static final Deviceswithoutidcomponentofdevicewithid DEVICESWITHOUTIDCOMPONENTOFDEVICEWITHID = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Deviceswithoutidcomponentofdevicewithid.DEVICESWITHOUTIDCOMPONENTOFDEVICEWITHID;

    /**
     * The table <code>trustalo.digitalinformationunits</code>.
     */
    public static final Digitalinformationunits DIGITALINFORMATIONUNITS = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Digitalinformationunits.DIGITALINFORMATIONUNITS;

    /**
     * The table <code>trustalo.hddmodels</code>.
     */
    public static final Hddmodels HDDMODELS = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Hddmodels.HDDMODELS;

    /**
     * The table <code>trustalo.people</code>.
     */
    public static final People PEOPLE = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.People.PEOPLE;

    /**
     * The table <code>trustalo.personcategories</code>.
     */
    public static final Personcategories PERSONCATEGORIES = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Personcategories.PERSONCATEGORIES;

    /**
     * The table <code>trustalo.printermodels</code>.
     */
    public static final Printermodels PRINTERMODELS = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Printermodels.PRINTERMODELS;

    /**
     * The table <code>trustalo.printertecnologies</code>.
     */
    public static final Printertecnologies PRINTERTECNOLOGIES = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Printertecnologies.PRINTERTECNOLOGIES;

    /**
     * The table <code>trustalo.rammodels</code>.
     */
    public static final Rammodels RAMMODELS = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Rammodels.RAMMODELS;

    /**
     * The table <code>trustalo.requeststates</code>.
     */
    public static final Requeststates REQUESTSTATES = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Requeststates.REQUESTSTATES;

    /**
     * The table <code>trustalo.screenmodels</code>.
     */
    public static final Screenmodels SCREENMODELS = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Screenmodels.SCREENMODELS;

    /**
     * The table <code>trustalo.screenresolutions</code>.
     */
    public static final Screenresolutions SCREENRESOLUTIONS = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Screenresolutions.SCREENRESOLUTIONS;

    /**
     * The table <code>trustalo.screentecnologies</code>.
     */
    public static final Screentecnologies SCREENTECNOLOGIES = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Screentecnologies.SCREENTECNOLOGIES;

    /**
     * The table <code>trustalo.trashwaredevicecategories</code>.
     */
    public static final Trashwaredevicecategories TRASHWAREDEVICECATEGORIES = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Trashwaredevicecategories.TRASHWAREDEVICECATEGORIES;

    /**
     * The table <code>trustalo.vendors</code>.
     */
    public static final Vendors VENDORS = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Vendors.VENDORS;

    /**
     * The table <code>trustalo.workercategories</code>.
     */
    public static final Workercategories WORKERCATEGORIES = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Workercategories.WORKERCATEGORIES;

    /**
     * The table <code>trustalo.workers</code>.
     */
    public static final Workers WORKERS = it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Workers.WORKERS;
}
