package todo.model.level;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.stream.IntStream;

import todo.model.level.inputs.InputGenerator;
import todo.utils.Checks;
import todo.vm.Value;
import todo.vm.instructions.Instruction;

public class LevelImpl implements Level {
    private final String title;
    private final String description;
    private final int number;
    private final int rows;
    private final int columns;
    // Reflection used because allowed instructions can't be instances, it would
    // cause problems for instructions with variables
    private final Set<Class<? extends Instruction>> allowedInstructions;
    private final List<Instruction> solution;
    private final List<Value> memoryAddresses;
    private final InputGenerator inputGenerator;

    private LevelImpl(final String title, final int number, final int rows, final int columns,
            final Set<Class<? extends Instruction>> allowed, final String description, final List<Instruction> solution,
            final List<Optional<Value>> values, final InputGenerator inputGenerator) {
        this.title = title;
        this.description = description;
        this.number = number;
        this.rows = rows;
        this.columns = columns;
        this.allowedInstructions = allowed;
        this.solution = solution;
        this.memoryAddresses = new ArrayList<>();
        this.inputGenerator = inputGenerator;
        values.forEach(opt -> this.memoryAddresses.add(opt.orElseGet(Value::empty)));
    }

    @Override
    public String getTitle() {
        return this.title;
    }

    @Override
    public String getDescription() {
        return this.description;
    }

    @Override
    public int getProgressiveNumber() {
        return this.number;
    }

    @Override
    public int getMemoryRows() {
        return this.rows;
    }

    @Override
    public int getMemoryColumns() {
        return this.columns;
    }

    @Override
    public Set<Class<? extends Instruction>> getAllowedInstructions() {
        return Collections.unmodifiableSet(this.allowedInstructions);
    }

    @Override
    public List<Instruction> getSolution() {
        return Collections.unmodifiableList(this.solution);
    }

    @Override
    public List<Value> getMemoryAddresses() {
        return this.memoryAddresses;
    }

    @Override
    public List<Value> getInput() {
        return this.inputGenerator.getNewInput();
    }

    /**
     * Equals checks only for title because levels are only generated by the
     * {@link LevelsStorage}, where they are put in a map with title as key.
     */
    @Override
    public boolean equals(final Object other) {
        return (other instanceof Level) && ((Level) other).getTitle().equals(this.title);
    }

    @Override
    public int hashCode() {
        return this.title.hashCode();
    }

    @Override
    public String toString() {
        return "Level: " + this.title;
    }

    public static class LevelBuilder {
        private String title;
        private int number;
        private int rows;
        private int columns;
        private final Set<Class<? extends Instruction>> allowedInstructions;
        private final List<Instruction> solution;
        private final List<Optional<Value>> addressesValues;
        private InputGenerator inputGenerator;
        private String description;
        private boolean rowsSet;
        private boolean columnsSet;
        private boolean alreadyBuilt;

        public LevelBuilder() {
            this.allowedInstructions = new HashSet<>();
            this.solution = new ArrayList<>();
            this.addressesValues = new ArrayList<>();
        }

        /**
         * Set the number of rows for the memory area.
         *
         * @param rows the number of rows
         * @return this {@link LevelBuilder}
         */
        public LevelBuilder setMemoryRows(final int rows) {
            Checks.require(rows >= 0, IllegalStateException.class);
            this.rows = rows;
            this.rowsSet = true;
            if (this.columnsSet) {
                setMemoryAddressesCount();
            }
            return this;
        }

        /**
         * Set the number of columns for the memory area.
         *
         * @param columns the number of columns
         * @return this {@link LevelBuilder}
         */
        public LevelBuilder setMemoryColumns(final int columns) {
            Checks.require(columns >= 0, IllegalStateException.class);
            this.columns = columns;
            this.columnsSet = true;
            if (this.rowsSet) {
                setMemoryAddressesCount();
            }
            return this;
        }

        /**
         * Set a new allowed instruction via his class, otherwise it would be tricky for
         * {@link Instruction}s that contain parameters.
         *
         * @param instruction the {@link Instruction} to add
         * @return this {@link LevelBuilder}
         */
        public LevelBuilder addAllowedInstruction(final Class<? extends Instruction> instruction) {
            this.allowedInstructions.add(Objects.requireNonNull(instruction));
            return this;
        }

        /**
         * Add a new {@link Instruction} to the solution.
         *
         * @param solution the {@link Instruction} to add
         * @return this {@link LevelBuilder}
         */
        public LevelBuilder addToSolution(final Instruction solution) {
            this.solution.add(Objects.requireNonNull(solution));
            return this;
        }

        /**
         * Add a new {@link Value} to the memory area.
         *
         * @param value the {@link Value} to add
         * @param index the index where to put the {@link Value}
         * @return this {@link LevelBuilder}
         */
        public LevelBuilder addValueToAddress(final Value value, final int index) {
            this.addressesValues.set(index, Optional.of(value));
            return this;
        }

        /**
         * Set the title.
         *
         * @param title the title
         * @return this {@link LevelBuilder}
         */
        public LevelBuilder setTitle(final String title) {
            this.title = Objects.requireNonNull(title);
            return this;
        }

        /**
         * Set the description.
         *
         * @param description the description
         * @return this {@link LevelBuilder}
         */
        public LevelBuilder setDescription(final String description) {
            this.description = Objects.requireNonNull(description);
            return this;
        }

        /**
         * Set the progressive number used by the menu.
         *
         * @param number the progressive number
         * @return this {@link LevelBuilder}
         */
        public LevelBuilder setNumber(final int number) {
            Checks.require(number > 0, IllegalStateException.class);
            this.number = number;
            return this;
        }

        /**
         * Set a new {@link InputGenerator}.
         *
         * @param generator the {@link InputGenerator}
         * @return this {@link LevelBuilder}
         */
        public LevelBuilder setInputGenerator(final InputGenerator generator) {
            this.inputGenerator = Objects.requireNonNull(generator);
            return this;
        }

        /**
         * Set the memory area using rows and columns previously set.
         *
         * @return this {@link LevelBuilder}
         */
        private LevelBuilder setMemoryAddressesCount() {
            this.addressesValues.clear();
            this.rowsSet = false;
            this.columnsSet = false;
            IntStream.range(0, this.rows * this.columns).forEach(i -> this.addressesValues.add(Optional.empty()));
            return this;
        }

        /**
         * Create a new {@link Level} instance.
         *
         * @return a new {@link Level}
         */
        public Level build() {
            Checks.require(!this.alreadyBuilt, UnsupportedOperationException.class,
                    "Can't build twice with the same Builder");
            this.alreadyBuilt = true;
            Checks.require(!this.rowsSet && !this.columnsSet, IllegalStateException.class);
            Checks.require(!this.allowedInstructions.isEmpty(), IllegalStateException.class);
            Checks.require(!this.solution.isEmpty(), IllegalStateException.class);
            this.solution.forEach(instr -> Checks.require(this.allowedInstructions.contains(instr.getClass()),
                    IllegalStateException.class));
            Objects.requireNonNull(this.title);
            Objects.requireNonNull(this.inputGenerator);
            Objects.requireNonNull(this.description);
            return new LevelImpl(this.title, this.number, this.rows, this.columns, this.allowedInstructions,
                    this.description, this.solution, this.addressesValues, this.inputGenerator);
        }
    }

}
