package controller.gui.menu;

import java.io.IOException;

import javafx.fxml.FXML;

/**
 * 
 * The controller associated to the menu's gui and fxml file. 
 *
 */
public interface GUIMenuController {

    /**
     * The handler for the click event generated by the 'start' button.
     * Shows the game's scene, sets the sound's setting and start the game.
     * 
     * @throws IOException
     *      if the name of the fxml is mispelled or if it doesn't exist
     */
    @FXML
    void startBtnOnClickHandler() throws IOException;

    /**
     * The handler for the click event generated by the 'leaderboard' button.
     * Shows the leaderboard's scene.
     * 
     * @throws IOException
     *      if the name of the fxml is mispelled or if it doesn't exist
     */
    @FXML
    void leaderboardBtnOnClickHandler() throws IOException;

    /**
     * The handler for the click event generated by the 'tutorial' button.
     * Shows the tutorial's scene.
     */
    @FXML
    void tutorialBtnOnClickHandler();

    /**
     * The handler for the click event generated by the 'settings' button.
     * Shows the settings' scene and initialize its controller.
     * 
     * @throws IOException 
     *      if the name of the fxml is mispelled or if it doesn't exist
     */
    @FXML
    void settingsBtnOnClickHandler() throws IOException;

    /**
     * The handler for the click event generated by the 'exit' button.
     * Shows the exit's scene.
     * 
     * @throws IOException 
     *          if the name of the fxml is mispelled or if it doesn't exist
     */
    @FXML
    void exitBtnOnClickHandler() throws IOException;
}
