package controller;

import java.util.Map;
import java.util.Set;

import model.GameModel;
import utils.Directions;
import utils.GhostUtils;
import utils.Pair;
import view.View;
/**
 * This class is used to simplify the update of mappable data.
 * Its task is to adapt data generated by model to data required by view.
 */
public class DataUpdater {

    private final GameModel model;
    private final View view;
    private final double levelDuration;
    private int finalLevel;
    private int finalScore;
    private boolean isGameEnded;
    /**
     * Constructor.
     * @param model
     *      the {@link GameModel} reference
     * @param view
     *      the {@link View} reference
     */
    public DataUpdater(final GameModel model, final View view) {
        this.model = model;
        this.view = view;
        this.levelDuration = this.model.getLevelDuration();
        this.initialize();
    }
    /**
     * Updates model.
     */
    public void updateModel() {
        this.model.moveEntitiesNextPosition();
    }
    /**
     * Updates view.
     */
    public void render() {
        this.view.render();
    }

    /**
     * @return true if the game is ended, false otherwise
     */
    public boolean isGameEnded() {
        if (this.model.isGameEnded()) {
            this.finalLevel = this.model.getLevelNumber();
            this.finalScore = this.model.getScores();
            this.isGameEnded = true;
            return this.isGameEnded;
        }
        this.isGameEnded = false;
        return this.isGameEnded;
    }
    /**
    *
    * @return true if the game is inverted, false otherwise
    */
    public boolean isGameInverted() {
        return this.model.isGameInverted();
    }
    /**
    *
    * @return the time of the inverted game
    */
    public int getInvertedGameTime() {
        return this.model.getInvertedGameTime();
    }
    /**
     * @return the X position of Pac-Man
     */
    public int getPacManXPosition() {
        return this.model.getPacManPosition().getX();
    }
    /**
     * @return the Y position of Pac-Man
     */
    public int getPacManYPosition() {
        return this.model.getPacManPosition().getY();
    }
    /**
     * @return the Pacman direction.
     */
    public Directions getPacManDirection() {
        return this.model.getPacManDirection();
    }
    /**
     * @return a value between 0 and 1 that indicates the level-timer progress. 
     */
    public double getLevelTimePercentage() {
        return this.model.getLevelTime() / this.levelDuration;
    }
    /**
     * @return the scores of the current game
     */
    public int getCurrentScore() {
        return this.isGameEnded ? this.finalScore : this.model.getScores();
    }
    /**
     * @return the level number
     */
    public int getLevel() {
        return this.isGameEnded ? this.finalLevel : this.model.getLevelNumber();
    }
    /**
     * @return the remaining lives of Pac-Man
     */
    public int getLives() {
        return this.model.getPacManLives();
    }
    /**
     * @return a Set containing the positions of the pills;
     */
    public Set<Pair<Integer, Integer>> getPillsPositions() {
        return this.model.getPillsPositions();
    }
    /**
     * @return a Set containing the wall's positions;
     */
    public Set<Pair<Integer, Integer>> getWallsPositions() {
        return this.model.getWallsPositions();
    }
    /**
     * @return a Map containing KEY -> Id, VALUE -> GhostUtils.
     */
    public Map<Integer, GhostUtils> getGhosts() {
        return this.model.getGhosts();
    }
    /**
     * @return the size of the map on the x-axis
     */
    public int getxMapSize() {
        return this.model.getxMapSize();
    }
    /**
     * @return the size of the map on the y-axis
     */
    public int getyMapSize() {
        return this.model.getyMapSize();
    }
    /**
     * Initialize DataUpdater.
     */
    public final void initialize() {
        this.isGameEnded = false;
        this.finalLevel = 0;
        this.finalScore = 0;
    }
}
