package controller.input;

import com.badlogic.gdx.InputProcessor;

import model.Fighter;
import model.Status;
import utility.KeyMapper;
import view.stage.FighterView;

/**
 * Manages the keyboard input
 */
public class KeyboardListener implements InputProcessor {

    private KeyMapper keyMap;
    private boolean flagAttack;
    private Fighter body;
    private FighterView view;
    private MovesetManager movesetManager;

    private static final float ZERO_MOVEMENT = 0;

    /**
     * Links the elements to create the correct body movements
     * @param bodyO
     *          the original body
     * @param view
     *          the view of the Fighters
     * @param keyMap
     *          the keymap generated by KeyMapper
     */
    public KeyboardListener(final Fighter bodyO, final FighterView view, final KeyMapper keyMap) {
        this.body =  bodyO;
        this.keyMap = keyMap;
        this.view = view;
        this.movesetManager = new MovesetManager(this, this.body, this.view, this.keyMap);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean keyDown(int keycode) {

        if (!this.body.getCurrentStatus().equals(Status.HIT)) {

            if (keycode == this.keyMap.getJump()) {
                this.movesetManager.jump();
            }

            if (keycode == this.keyMap.getAttack()) {
                this.movesetManager.attack();
            }

            if (this.movesetManager.enter(keycode)) {
                this.movesetManager.doMovement();
            }
        }
        return false;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean keyUp(int keycode) {
        if (!this.body.getCurrentStatus().equals(Status.HIT)) {
            if (this.movesetManager.exit(keycode) || keycode == this.keyMap.getJump() || !this.flagAttack) {
            	if (!this.movesetManager.getBuffer().isEmpty()) {
                    this.movesetManager.doMovement();
                } else {
                    this.body.getBody().setLinearVelocity(ZERO_MOVEMENT, this.body.getBody().getLinearVelocity().y);
                    this.body.setCurrentStatus(Status.IDLE);
                }
            }
        }
        if (this.body.getCurrentStatus().equals(Status.HIT)) {
        	this.movesetManager.getBuffer().clear();
        	
        }
        return false;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean keyTyped(char character) {
        return false;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean touchDown(int screenX, int screenY, int pointer, int button) {
        return false;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean touchUp(int screenX, int screenY, int pointer, int button) {
        return false;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean touchDragged(int screenX, int screenY, int pointer) {
        return false;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean mouseMoved(int screenX, int screenY) {
        return false;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean scrolled(int amount) {
        return false;
    }

    /**
     * @return the attack flag
     */
    public boolean getFlagAttack() {
        return this.flagAttack;
    }

    /**
     * @param flagAttack
     *      sets the attack flag
     */
    public void setFlagAttack(final boolean flagAttack) {
        this.flagAttack = flagAttack;
    }
}