package it.unibo.elementsduo.model.interactions.core.impl;

import java.util.ArrayList;
import java.util.List;

import it.unibo.elementsduo.model.interactions.commands.api.InteractionCommand;

/**
 * Represents a collection of interaction responses generated by different
 * handlers.
 * 
 * <p>
 * The {@code InteractionResponse} groups and executes both physics-related and
 * logic-related collision commands in a specific order.
 */
public final class InteractionResponse {

    /** The list of physics-related interaction commands. */
    private final List<InteractionCommand> physicsCommands;

    /** The list of logic-related interaction commands. */
    private final List<InteractionCommand> logicCommands;

    /**
     * Creates a new {@code InteractionResponse} containing the given command lists.
     *
     * @param physicsCommands the list of physics-related commands
     * @param logicCommands   the list of logic-related commands
     */
    private InteractionResponse(final List<InteractionCommand> physicsCommands,
            final List<InteractionCommand> logicCommands) {
        this.physicsCommands = List.copyOf(physicsCommands);
        this.logicCommands = List.copyOf(logicCommands);
    }

    /**
     * Executes all registered Interaction commands in order.
     * 
     * <p>
     * Physics commands are executed first, followed by logic commands.
     */
    public void execute() {
        this.physicsCommands.forEach(InteractionCommand::execute);
        this.logicCommands.forEach(InteractionCommand::execute);
    }

    /**
     * Builder class for constructing {@link InteractionResponse} instances.
     * 
     * <p>
     * Use this builder to collect physics and logic commands before creating the
     * final response object.
     */
    public static final class Builder {

        private final List<InteractionCommand> physicsCommands = new ArrayList<>();
        private final List<InteractionCommand> logicCommands = new ArrayList<>();

        /**
         * Adds a logic-related command to the response.
         *
         * @param command the logic command to add
         */
        public void addLogicCommand(final InteractionCommand command) {
            this.logicCommands.add(command);
        }

        /**
         * Adds a physics-related command to the response.
         *
         * @param command the physics command to add
         */
        public void addPhysicsCommand(final InteractionCommand command) {
            this.physicsCommands.add(command);
        }

        /**
         * Builds a new {@link InteractionResponse} instance containing all
         * accumulated commands.
         *
         * @return a new {@code InteractionResponse} instance
         */
        public InteractionResponse build() {
            return new InteractionResponse(this.physicsCommands, this.logicCommands);
        }
    }
}
