package controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.Pane;

/**
 * This is the controller for the help page
 */
public class HelpController {

    @FXML
    private BorderPane rootPane;

    /**
     * The handler for the click event generated by the 'Home' ImageView.
     *
     * @throws Exception only if FXMLLoader.load() fails to load the page
     */
    @FXML
    public void backHome() throws Exception{
        System.out.println("Home!!!");
        Pane pane = FXMLLoader.load(ClassLoader.getSystemResource("layouts/main.fxml"));
        rootPane.getChildren().setAll(pane);
    }
}
