package controller;

import javafx.animation.PathTransition;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.geometry.Insets;
import javafx.scene.control.ContentDisplay;
import javafx.scene.control.Label;
import javafx.scene.image.ImageView;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.Pane;
import javafx.scene.shape.Line;
import javafx.util.Duration;
import model.player.PlayersCollectionImpl;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;


/**
 * The Controller related to the main.fxml GUI.
 *
 */
public final class UIController implements Initializable  {

    @FXML
    private BorderPane container;

    @FXML
    private Label top_score;

    @FXML
    private ImageView BBTAN_bot;

    @FXML
    private Insets marginOverBall;

    @FXML
    private ImageView ball;

    @FXML
    private ImageView play;

    /**
     * The handler for the click event generated by the 'help' ImageView.
     *
     * @throws IOException only if FXMLLoader.load() fails to load the page
     */
    @FXML
    public void clickHelp() throws IOException {
        System.out.println("HELP!!!!");
        Pane pane = FXMLLoader.load(ClassLoader.getSystemResource("layouts/helpPage.fxml"));
        container.getChildren().setAll(pane);
    }

    /**
     * The handler for the click event generated by the 'stats' ImageView.
     *
     * @throws IOException only if FXMLLoader.load() fails to load the page
     */
    @FXML
    public void clickStats() throws IOException{
        System.out.println("Stats!!!!");
        Pane pane = FXMLLoader.load(ClassLoader.getSystemResource("layouts/leaderboard.fxml"));
        container.getChildren().setAll(pane);
    }

    /**
     * The handler for the click event generated by the 'player' ImageView.
     *
     * @throws IOException only if FXMLLoader.load() fails to load the page
     */
    @FXML
    public void clickPlayer() throws  IOException{
        System.out.println("Player!!!!");
        Pane pane = FXMLLoader.load(ClassLoader.getSystemResource("layouts/playerInsertionPage.fxml"));
        container.getChildren().setAll(pane);
    }

    /**
     * The handler for the click event generated by the 'Play' ImageView.
     *
     * @throws IOException only if FXMLLoader.load() fails to load the page
     */
    @FXML
    public void clickPlay() throws IOException {
        System.out.println("PLAY!!!");
        BorderPane pane = FXMLLoader.load(ClassLoader.getSystemResource("layouts/blockPage.fxml"));
        container.setTop(pane.getTop());
        container.setCenter(pane.getCenter());
    }

    /**
     * The handler for the click event generated by the 'Shop' ImageView.
     *
     * @throws IOException only if FXMLLoader.load() fails to load the page
     */
    @FXML
    public void clickShop() throws IOException{
        System.out.println("SHOP!!!");
        //re-direct to the future shop page
    }

    @Override
    public void initialize(URL location, ResourceBundle resources) {
        System.out.println("start initialize main page");
        startAnimationBBTAN();
        startAnimationBall();

        /*
        Label bestScore = new Label("My Label");
        Label name = new Label("My Label");

        var players = PlayersCollectionImpl.getLeaderboard();
        if(players.getCurrentPlayer().isPresent()){
            bestScore.setText(""+players.getCurrentPlayer().get().getBestScore());
            name.setText(players.getCurrentPlayer().get().getName());
        }
        else{
            bestScore.setText(""+players.getBestPlayer().getBestScore());
            name.setText("Sign Up");
        }

        bestScore.setContentDisplay(ContentDisplay.TOP);
        name.setContentDisplay(ContentDisplay.RIGHT);


        top_score.setText(""+players.getBestPlayer().getBestScore());*/

    }

    //Method to animate BBTAN_bot
    private void startAnimationBBTAN(){
        Line direct = new Line(-BBTAN_bot.getFitWidth()*3/8, BBTAN_bot.getFitHeight()/2, BBTAN_bot.getFitWidth()*5/8, BBTAN_bot.getFitHeight()/2);
        startAnimation(direct, BBTAN_bot, 4000);
    }

    //Method to animate ball
    private void startAnimationBall(){
        Line direct = new Line(play.getFitWidth()*3/5, -1.0, play.getFitWidth()*3/5, (-marginOverBall.getBottom())+3);
        startAnimation(direct, ball, 350);
    }

    //Method to animate an ImageView in Line with time with Javafx Animation
    private void startAnimation(Line direct, ImageView image, int time){
        PathTransition transition = new PathTransition();
        transition.setNode(image);
        transition.setDuration(Duration.millis(time));
        transition.setPath(direct);
        transition.setAutoReverse(true);
        transition.setCycleCount(PathTransition.INDEFINITE);
        transition.play();
    }
}
