package controller.gui.gameOver;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

public interface GUIGameOver1Controller {

    /**
     * The handler for the click event generated by the 'Re-start' button. A new
     * game will start.
     * 
     * @throws IOException
     *                         if the name of the fxml is wrong
     */
    void saveBtnOnClickHandler() throws IOException;

    /**
     * The handler for the click event generated by the 'Re-start' button. A new
     * game will start.
     * 
     * @throws IOException
     *                         if the name of the fxml is wrong
     */
    void reStartBtnOnClickHandler() throws IOException;

    /**
     * The handler for the click event generated by the 'menu' button. go back to
     * the main menu.
     * 
     * @throws IOException
     *                         if the name of the fxml is wrong
     */
    void menuBtnOnClickHandler() throws IOException;

    /**
     * The handler for the click event generated by the 'leaderboard' button go to
     * see your place in the leaderboard.
     * 
     * @throws IOException
     *                         if the name of the fxml is wrong
     */
    void leaderBtnOnClickHandler() throws IOException;

    /**
     * This method set all the gameOver's label: time, score, position on the
     * Leaderboard. Control over the player's nickname.
     *
     * 
     * @param location
     * @param resources
     */
    void initialize(URL location, ResourceBundle resources);

}
