/*
 * This file was generated by the Gradle "init" task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the "Building Java & JVM projects" chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3/userguide/building_java_projects.html
 */

import de.aaschmid.gradle.plugins.cpd.Cpd


plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.openjfx.javafxplugin") version "0.0.13"
    id("com.github.johnrengelman.shadow") version "7.1.2"
    id("org.danilopianini.gradle-java-qa") version "1.6.0"
    alias(libs.plugins.taskTree)
}


java {
  toolchain {
    languageVersion.set(JavaLanguageVersion.of(17))
  }
}


tasks.javadoc {
    isFailOnError = false
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    jcenter()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")

    // JavaFX
    implementation(group="org.openjfx", name="javafx-base", version="17", classifier="win")
    implementation(group="org.openjfx", name="javafx-base", version="17", classifier="mac")
    implementation(group="org.openjfx", name="javafx-base", version="17", classifier="linux")
    implementation(group="org.openjfx", name="javafx-controls", version="17", classifier="win")
    implementation(group="org.openjfx", name="javafx-controls", version="17", classifier="mac")
    implementation(group="org.openjfx", name="javafx-controls", version="17", classifier="linux")
    implementation(group="org.openjfx", name="javafx-fxml", version="17", classifier="win")
    implementation(group="org.openjfx", name="javafx-fxml", version="17", classifier="mac")
    implementation(group="org.openjfx", name="javafx-fxml", version="17", classifier="linux")
    implementation(group="org.openjfx", name="javafx-graphics", version="17", classifier="win")
    implementation(group="org.openjfx", name="javafx-graphics", version="17", classifier="mac")
    implementation(group="org.openjfx", name="javafx-graphics", version="17", classifier="linux")

    // Use JUnit Jupiter Engine for testing.
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.9.1")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")

    // Use yaml
    implementation("org.yaml:snakeyaml:2.0")

    // spotbugs
    compileOnly("com.github.spotbugs:spotbugs-annotations:4.7.3")

}

spotbugs {
    ignoreFailures.set(true)
    // showStackTraces.set(false)
}

application {
    // Define the main class for the application.
    mainClass.set("powpaw.Main")
}

sourceSets {
    main {
        resources {
            srcDirs("src/assets")
            srcDirs("src/main/java/powpaw/config")
        }
    }
}

val test by tasks.getting(Test::class) {
    // Use junit platform for unit tests
    useJUnitPlatform()
    testLogging {
        events(*(org.gradle.api.tasks.testing.logging.TestLogEvent.values())) // events("passed", "skipped", "failed")
    }
    testLogging.showStandardStreams = true    
}
