package view.stage;

import com.badlogic.gdx.graphics.g2d.Animation;
import com.badlogic.gdx.graphics.g2d.TextureRegion;
import model.Status;
import utility.AnimationGenerator;
import java.util.HashMap;

/**
 * Links the animations generated by AnimationGenerator to every Status a Fighter can have using a HashMap
 *
 */
public class AnimationManager {

    private final String playerName;
    private HashMap<Status,Animation<TextureRegion>> stageMap;
    /**
     * Creates a HashMap and populates it with Status and Animation<TextureRegion>
     * @param playerName
     */
    public AnimationManager(final String playerName) {
        this.playerName = playerName;
        this.stageMap = new HashMap<Status, Animation<TextureRegion>>();
        this.mapGenerator();
    }

    /**
     * @param status
     * @return the animation in the map linked to the status given
     */
    public Animation<TextureRegion>  getAnimation(final Status status) {
        return stageMap.get(status);
    }

    /**
     * Populates the Map linking each Status his correct Animation<TextureRegion>
     */
    private void mapGenerator() {
        for (Status status: Status.values()) {
            stageMap.put(status, new AnimationGenerator(this.playerName + "/" + status.getString()).getAnimation());
        }
    }

}
