package jvmt.view.modal.api;

/**
 * Models a modal that blocks user interaction over a main
 * window until the user provides an input.
 * 
 * @param <T> the type of the user input returned by the modal.
 * 
 * @author Emir Wanes Aouioua
 */
public interface Modal<T> {

    /**
     * Blocks the interaction with the parent window and
     * waits until the user provides an input.
     */
    void waitUserInput();

    /**
     * Returns the input provided/generated by the user interaction
     * after {@link #waitUserInput()} has completed.
     * 
     * @return the value representing the user's input.
     * @throws IllegalStateException if called before {@link #waitUserInput()}.
     */
    T getUserInput();
}
