/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package powpaw;

import javafx.application.Application;
import javafx.stage.Stage;
import powpaw.core.controller.StaticGameState;

/**
 * Main app.
 */
public final class App extends Application {
    /**
     * Main.
     * 
     * @param args
     */
    public static void main(final String[] args) {
        Application.launch(App.class, args);
    }

    @Override
    public void start(final Stage primaryStage) throws Exception {
        StaticGameState.getGameStateView().showStartMenu();
    }
}
