package bubbleshooter.view.scene.controller;

import bubbleshooter.controller.Controller;
import bubbleshooter.utility.Settings;
import bubbleshooter.view.View;
import bubbleshooter.view.scene.FXMLPath;
import javafx.fxml.FXML;
import javafx.geometry.Pos;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.text.Font;
import javafx.scene.text.TextAlignment;

/**
 * The Controller related to the pause.fxml GUI.
 */
public class PauseController extends AbstractController {

    @FXML private Label titleLabel;
    @FXML private Button resumeButton;
    @FXML private Button restartButton;
    @FXML private Button quitButton;

    private static final double TITLE_DISTANCE = Settings.getGuiHeight() / 10;
    private static final double TITLE_HEIGHT = Settings.getGuiHeight() / 8;
    private static final double TITLE_WIDTH = Settings.getGuiWidth();
    private static final double TITLE_FONT_SIZE = TITLE_HEIGHT / 1.5;
    private static final double BUTTON_DISTANCE = Settings.getGuiHeight() / 50;
    private static final double BUTTON_WIDTH = Settings.getGuiWidth() / 2;
    private static final double BUTTON_HEIGHT = Settings.getGuiHeight() / 10;
    private static final double BUTTON_X = Settings.getGuiWidth() / 2 - BUTTON_WIDTH / 2;
    private static final double BUTTON_FONT_SIZE = BUTTON_HEIGHT / 2.5;

    @Override
    public final void init(final Controller controller, final View view) {
        this.setController(controller);
        this.setView(view);

        this.titleLabel.setText("Pause");
        this.titleLabel.setFont(Font.font(TITLE_FONT_SIZE));
        this.titleLabel.setAlignment(Pos.BOTTOM_CENTER);
        this.titleLabel.setPrefSize(TITLE_WIDTH, TITLE_HEIGHT);

        this.resumeButton.setText("Resume");
        this.resumeButton.setTextAlignment(TextAlignment.CENTER);
        this.resumeButton.setLayoutX(BUTTON_X);
        this.resumeButton.setLayoutY(TITLE_HEIGHT + TITLE_DISTANCE);
        this.resumeButton.setPrefSize(BUTTON_WIDTH, BUTTON_HEIGHT);
        this.resumeButton.setFont(Font.font(BUTTON_FONT_SIZE));

        this.restartButton.setText("Restart");
        this.restartButton.setTextAlignment(TextAlignment.CENTER);
        this.restartButton.setLayoutX(BUTTON_X);
        this.restartButton.setLayoutY(this.resumeButton.getLayoutY() + BUTTON_HEIGHT + BUTTON_DISTANCE);
        this.restartButton.setPrefSize(BUTTON_WIDTH, BUTTON_HEIGHT);
        this.restartButton.setFont(Font.font(BUTTON_FONT_SIZE));

        this.quitButton.setText("Quit");
        this.quitButton.setTextAlignment(TextAlignment.CENTER);
        this.quitButton.setLayoutX(BUTTON_X);
        this.quitButton.setLayoutY(this.restartButton.getLayoutY() + BUTTON_HEIGHT + BUTTON_DISTANCE);
        this.quitButton.setPrefSize(BUTTON_WIDTH, BUTTON_HEIGHT);
        this.quitButton.setFont(Font.font(BUTTON_FONT_SIZE));

    }

    /**
     * The handler for the click event generated by the 'resumeButton' button.
     */
    @FXML
    public final void resume() {
        this.getController().getGameEngine().resumeLoop();
        this.setNextScene(FXMLPath.GAME);
        this.loadNextScene();
    }

    /**
     * The handler for the click event generated by the 'restartButton' button.
     */
    @FXML
    public final void restart() {
        this.getController().startGame(this.getController().getCurrentLevel());
        this.setNextScene(FXMLPath.GAME);
        this.loadNextScene();
    }

    /**
     * The handler for the click event generated by the 'quitButton' button.
     */
    @FXML
    public final void quit() {
        System.exit(0);
    }
}
