/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Aspectratios;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AspectratiosRecord extends UpdatableRecordImpl<AspectratiosRecord> implements Record2<UByte, String> {

    private static final long serialVersionUID = -385434395;

    /**
     * Setter for <code>trustalo.aspectratios.ID</code>.
     */
    public void setId(UByte value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustalo.aspectratios.ID</code>.
     */
    public UByte getId() {
        return (UByte) get(0);
    }

    /**
     * Setter for <code>trustalo.aspectratios.RatioFactor</code>.
     */
    public void setRatiofactor(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustalo.aspectratios.RatioFactor</code>.
     */
    public String getRatiofactor() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UByte> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<UByte, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<UByte, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field1() {
        return Aspectratios.ASPECTRATIOS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Aspectratios.ASPECTRATIOS.RATIOFACTOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getRatiofactor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRatiofactor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AspectratiosRecord value1(UByte value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AspectratiosRecord value2(String value) {
        setRatiofactor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AspectratiosRecord values(UByte value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AspectratiosRecord
     */
    public AspectratiosRecord() {
        super(Aspectratios.ASPECTRATIOS);
    }

    /**
     * Create a detached, initialised AspectratiosRecord
     */
    public AspectratiosRecord(UByte id, String ratiofactor) {
        super(Aspectratios.ASPECTRATIOS);

        set(0, id);
        set(1, ratiofactor);
    }
}
