/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Colors;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ColorsRecord extends UpdatableRecordImpl<ColorsRecord> implements Record2<UByte, String> {

    private static final long serialVersionUID = -867589843;

    /**
     * Setter for <code>trustalo.colors.ID</code>.
     */
    public void setId(UByte value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustalo.colors.ID</code>.
     */
    public UByte getId() {
        return (UByte) get(0);
    }

    /**
     * Setter for <code>trustalo.colors.HexCode</code>.
     */
    public void setHexcode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustalo.colors.HexCode</code>.
     */
    public String getHexcode() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UByte> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<UByte, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<UByte, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field1() {
        return Colors.COLORS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Colors.COLORS.HEXCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getHexcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getHexcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ColorsRecord value1(UByte value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ColorsRecord value2(String value) {
        setHexcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ColorsRecord values(UByte value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ColorsRecord
     */
    public ColorsRecord() {
        super(Colors.COLORS);
    }

    /**
     * Create a detached, initialised ColorsRecord
     */
    public ColorsRecord(UByte id, String hexcode) {
        super(Colors.COLORS);

        set(0, id);
        set(1, hexcode);
    }
}
