/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Contacts;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContactsRecord extends UpdatableRecordImpl<ContactsRecord> implements Record4<UByte, UInteger, String, UInteger> {

    private static final long serialVersionUID = -1862242982;

    /**
     * Setter for <code>trustalo.contacts.Category</code>.
     */
    public void setCategory(UByte value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustalo.contacts.Category</code>.
     */
    public UByte getCategory() {
        return (UByte) get(0);
    }

    /**
     * Setter for <code>trustalo.contacts.Person</code>.
     */
    public void setPerson(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustalo.contacts.Person</code>.
     */
    public UInteger getPerson() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>trustalo.contacts.Value</code>.
     */
    public void setValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustalo.contacts.Value</code>.
     */
    public String getValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>trustalo.contacts.ID</code>.
     */
    public void setId(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>trustalo.contacts.ID</code>.
     */
    public UInteger getId() {
        return (UInteger) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UByte, UInteger, String, UInteger> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UByte, UInteger, String, UInteger> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field1() {
        return Contacts.CONTACTS.CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return Contacts.CONTACTS.PERSON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Contacts.CONTACTS.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field4() {
        return Contacts.CONTACTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component1() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getPerson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component4() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value1() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getPerson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value4() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactsRecord value1(UByte value) {
        setCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactsRecord value2(UInteger value) {
        setPerson(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactsRecord value3(String value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactsRecord value4(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactsRecord values(UByte value1, UInteger value2, String value3, UInteger value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContactsRecord
     */
    public ContactsRecord() {
        super(Contacts.CONTACTS);
    }

    /**
     * Create a detached, initialised ContactsRecord
     */
    public ContactsRecord(UByte category, UInteger person, String value, UInteger id) {
        super(Contacts.CONTACTS);

        set(0, category);
        set(1, person);
        set(2, value);
        set(3, id);
    }
}
