/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Devicecategoryallowedcomponents;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DevicecategoryallowedcomponentsRecord extends UpdatableRecordImpl<DevicecategoryallowedcomponentsRecord> implements Record3<UByte, UByte, UByte> {

    private static final long serialVersionUID = 1402650820;

    /**
     * Setter for <code>trustalo.devicecategoryallowedcomponents.ID</code>.
     */
    public void setId(UByte value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustalo.devicecategoryallowedcomponents.ID</code>.
     */
    public UByte getId() {
        return (UByte) get(0);
    }

    /**
     * Setter for <code>trustalo.devicecategoryallowedcomponents.CompoundCategory</code>.
     */
    public void setCompoundcategory(UByte value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustalo.devicecategoryallowedcomponents.CompoundCategory</code>.
     */
    public UByte getCompoundcategory() {
        return (UByte) get(1);
    }

    /**
     * Setter for <code>trustalo.devicecategoryallowedcomponents.ComponentCategory</code>.
     */
    public void setComponentcategory(UByte value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustalo.devicecategoryallowedcomponents.ComponentCategory</code>.
     */
    public UByte getComponentcategory() {
        return (UByte) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UByte> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UByte, UByte, UByte> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UByte, UByte, UByte> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field1() {
        return Devicecategoryallowedcomponents.DEVICECATEGORYALLOWEDCOMPONENTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field2() {
        return Devicecategoryallowedcomponents.DEVICECATEGORYALLOWEDCOMPONENTS.COMPOUNDCATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field3() {
        return Devicecategoryallowedcomponents.DEVICECATEGORYALLOWEDCOMPONENTS.COMPONENTCATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component2() {
        return getCompoundcategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component3() {
        return getComponentcategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value2() {
        return getCompoundcategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value3() {
        return getComponentcategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicecategoryallowedcomponentsRecord value1(UByte value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicecategoryallowedcomponentsRecord value2(UByte value) {
        setCompoundcategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicecategoryallowedcomponentsRecord value3(UByte value) {
        setComponentcategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicecategoryallowedcomponentsRecord values(UByte value1, UByte value2, UByte value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DevicecategoryallowedcomponentsRecord
     */
    public DevicecategoryallowedcomponentsRecord() {
        super(Devicecategoryallowedcomponents.DEVICECATEGORYALLOWEDCOMPONENTS);
    }

    /**
     * Create a detached, initialised DevicecategoryallowedcomponentsRecord
     */
    public DevicecategoryallowedcomponentsRecord(UByte id, UByte compoundcategory, UByte componentcategory) {
        super(Devicecategoryallowedcomponents.DEVICECATEGORYALLOWEDCOMPONENTS);

        set(0, id);
        set(1, compoundcategory);
        set(2, componentcategory);
    }
}
