/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Devicerequestdetails;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DevicerequestdetailsRecord extends UpdatableRecordImpl<DevicerequestdetailsRecord> implements Record6<UInteger, UInteger, String, String, UByte, UInteger> {

    private static final long serialVersionUID = 314809188;

    /**
     * Setter for <code>trustalo.devicerequestdetails.ID</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustalo.devicerequestdetails.ID</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>trustalo.devicerequestdetails.Request</code>.
     */
    public void setRequest(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustalo.devicerequestdetails.Request</code>.
     */
    public UInteger getRequest() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>trustalo.devicerequestdetails.Category</code>.
     */
    public void setCategory(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustalo.devicerequestdetails.Category</code>.
     */
    public String getCategory() {
        return (String) get(2);
    }

    /**
     * Setter for <code>trustalo.devicerequestdetails.Annotations</code>.
     */
    public void setAnnotations(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>trustalo.devicerequestdetails.Annotations</code>.
     */
    public String getAnnotations() {
        return (String) get(3);
    }

    /**
     * Setter for <code>trustalo.devicerequestdetails.Quantity</code>.
     */
    public void setQuantity(UByte value) {
        set(4, value);
    }

    /**
     * Getter for <code>trustalo.devicerequestdetails.Quantity</code>.
     */
    public UByte getQuantity() {
        return (UByte) get(4);
    }

    /**
     * Setter for <code>trustalo.devicerequestdetails.ComponentOfRequestDevice</code>.
     */
    public void setComponentofrequestdevice(UInteger value) {
        set(5, value);
    }

    /**
     * Getter for <code>trustalo.devicerequestdetails.ComponentOfRequestDevice</code>.
     */
    public UInteger getComponentofrequestdevice() {
        return (UInteger) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, UInteger, String, String, UByte, UInteger> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, UInteger, String, String, UByte, UInteger> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Devicerequestdetails.DEVICEREQUESTDETAILS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return Devicerequestdetails.DEVICEREQUESTDETAILS.REQUEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Devicerequestdetails.DEVICEREQUESTDETAILS.CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Devicerequestdetails.DEVICEREQUESTDETAILS.ANNOTATIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field5() {
        return Devicerequestdetails.DEVICEREQUESTDETAILS.QUANTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field6() {
        return Devicerequestdetails.DEVICEREQUESTDETAILS.COMPONENTOFREQUESTDEVICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getRequest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAnnotations();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component5() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component6() {
        return getComponentofrequestdevice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getRequest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAnnotations();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value5() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value6() {
        return getComponentofrequestdevice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicerequestdetailsRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicerequestdetailsRecord value2(UInteger value) {
        setRequest(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicerequestdetailsRecord value3(String value) {
        setCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicerequestdetailsRecord value4(String value) {
        setAnnotations(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicerequestdetailsRecord value5(UByte value) {
        setQuantity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicerequestdetailsRecord value6(UInteger value) {
        setComponentofrequestdevice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicerequestdetailsRecord values(UInteger value1, UInteger value2, String value3, String value4, UByte value5, UInteger value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DevicerequestdetailsRecord
     */
    public DevicerequestdetailsRecord() {
        super(Devicerequestdetails.DEVICEREQUESTDETAILS);
    }

    /**
     * Create a detached, initialised DevicerequestdetailsRecord
     */
    public DevicerequestdetailsRecord(UInteger id, UInteger request, String category, String annotations, UByte quantity, UInteger componentofrequestdevice) {
        super(Devicerequestdetails.DEVICEREQUESTDETAILS);

        set(0, id);
        set(1, request);
        set(2, category);
        set(3, annotations);
        set(4, quantity);
        set(5, componentofrequestdevice);
    }
}
