/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Deviceswithid;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeviceswithidRecord extends UpdatableRecordImpl<DeviceswithidRecord> implements Record9<UInteger, UShort, UInteger, UByte, Byte, UByte, UInteger, String, Timestamp> {

    private static final long serialVersionUID = -2016082016;

    /**
     * Setter for <code>trustalo.deviceswithid.ID</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustalo.deviceswithid.ID</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>trustalo.deviceswithid.CategoryDeviceID</code>.
     */
    public void setCategorydeviceid(UShort value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustalo.deviceswithid.CategoryDeviceID</code>.
     */
    public UShort getCategorydeviceid() {
        return (UShort) get(1);
    }

    /**
     * Setter for <code>trustalo.deviceswithid.DeviceModel</code>.
     */
    public void setDevicemodel(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustalo.deviceswithid.DeviceModel</code>.
     */
    public UInteger getDevicemodel() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>trustalo.deviceswithid.Category</code>.
     */
    public void setCategory(UByte value) {
        set(3, value);
    }

    /**
     * Getter for <code>trustalo.deviceswithid.Category</code>.
     */
    public UByte getCategory() {
        return (UByte) get(3);
    }

    /**
     * Setter for <code>trustalo.deviceswithid.Available</code>.
     */
    public void setAvailable(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>trustalo.deviceswithid.Available</code>.
     */
    public Byte getAvailable() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>trustalo.deviceswithid.CurrentState</code>.
     */
    public void setCurrentstate(UByte value) {
        set(5, value);
    }

    /**
     * Getter for <code>trustalo.deviceswithid.CurrentState</code>.
     */
    public UByte getCurrentstate() {
        return (UByte) get(5);
    }

    /**
     * Setter for <code>trustalo.deviceswithid.LastUpdateWorker</code>.
     */
    public void setLastupdateworker(UInteger value) {
        set(6, value);
    }

    /**
     * Getter for <code>trustalo.deviceswithid.LastUpdateWorker</code>.
     */
    public UInteger getLastupdateworker() {
        return (UInteger) get(6);
    }

    /**
     * Setter for <code>trustalo.deviceswithid.Annotations</code>.
     */
    public void setAnnotations(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>trustalo.deviceswithid.Annotations</code>.
     */
    public String getAnnotations() {
        return (String) get(7);
    }

    /**
     * Setter for <code>trustalo.deviceswithid.LastUpdateDate</code>.
     */
    public void setLastupdatedate(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>trustalo.deviceswithid.LastUpdateDate</code>.
     */
    public Timestamp getLastupdatedate() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<UInteger, UShort, UInteger, UByte, Byte, UByte, UInteger, String, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<UInteger, UShort, UInteger, UByte, Byte, UByte, UInteger, String, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Deviceswithid.DEVICESWITHID.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UShort> field2() {
        return Deviceswithid.DEVICESWITHID.CATEGORYDEVICEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return Deviceswithid.DEVICESWITHID.DEVICEMODEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field4() {
        return Deviceswithid.DEVICESWITHID.CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return Deviceswithid.DEVICESWITHID.AVAILABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field6() {
        return Deviceswithid.DEVICESWITHID.CURRENTSTATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field7() {
        return Deviceswithid.DEVICESWITHID.LASTUPDATEWORKER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Deviceswithid.DEVICESWITHID.ANNOTATIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Deviceswithid.DEVICESWITHID.LASTUPDATEDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort component2() {
        return getCategorydeviceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component3() {
        return getDevicemodel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component4() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component5() {
        return getAvailable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component6() {
        return getCurrentstate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component7() {
        return getLastupdateworker();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getAnnotations();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getLastupdatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort value2() {
        return getCategorydeviceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getDevicemodel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value4() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getAvailable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value6() {
        return getCurrentstate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value7() {
        return getLastupdateworker();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getAnnotations();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getLastupdatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceswithidRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceswithidRecord value2(UShort value) {
        setCategorydeviceid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceswithidRecord value3(UInteger value) {
        setDevicemodel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceswithidRecord value4(UByte value) {
        setCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceswithidRecord value5(Byte value) {
        setAvailable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceswithidRecord value6(UByte value) {
        setCurrentstate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceswithidRecord value7(UInteger value) {
        setLastupdateworker(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceswithidRecord value8(String value) {
        setAnnotations(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceswithidRecord value9(Timestamp value) {
        setLastupdatedate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceswithidRecord values(UInteger value1, UShort value2, UInteger value3, UByte value4, Byte value5, UByte value6, UInteger value7, String value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DeviceswithidRecord
     */
    public DeviceswithidRecord() {
        super(Deviceswithid.DEVICESWITHID);
    }

    /**
     * Create a detached, initialised DeviceswithidRecord
     */
    public DeviceswithidRecord(UInteger id, UShort categorydeviceid, UInteger devicemodel, UByte category, Byte available, UByte currentstate, UInteger lastupdateworker, String annotations, Timestamp lastupdatedate) {
        super(Deviceswithid.DEVICESWITHID);

        set(0, id);
        set(1, categorydeviceid);
        set(2, devicemodel);
        set(3, category);
        set(4, available);
        set(5, currentstate);
        set(6, lastupdateworker);
        set(7, annotations);
        set(8, lastupdatedate);
    }
}
