/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Deviceswithoutidcomponentofdevicewithid;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeviceswithoutidcomponentofdevicewithidRecord extends UpdatableRecordImpl<DeviceswithoutidcomponentofdevicewithidRecord> implements Record3<UInteger, UInteger, UShort> {

    private static final long serialVersionUID = 1996675250;

    /**
     * Setter for <code>trustalo.deviceswithoutidcomponentofdevicewithid.Compound</code>.
     */
    public void setCompound(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustalo.deviceswithoutidcomponentofdevicewithid.Compound</code>.
     */
    public UInteger getCompound() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>trustalo.deviceswithoutidcomponentofdevicewithid.Component</code>.
     */
    public void setComponent(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustalo.deviceswithoutidcomponentofdevicewithid.Component</code>.
     */
    public UInteger getComponent() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>trustalo.deviceswithoutidcomponentofdevicewithid.Quantity</code>.
     */
    public void setQuantity(UShort value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustalo.deviceswithoutidcomponentofdevicewithid.Quantity</code>.
     */
    public UShort getQuantity() {
        return (UShort) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<UInteger, UInteger> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UInteger, UShort> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UInteger, UShort> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Deviceswithoutidcomponentofdevicewithid.DEVICESWITHOUTIDCOMPONENTOFDEVICEWITHID.COMPOUND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return Deviceswithoutidcomponentofdevicewithid.DEVICESWITHOUTIDCOMPONENTOFDEVICEWITHID.COMPONENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UShort> field3() {
        return Deviceswithoutidcomponentofdevicewithid.DEVICESWITHOUTIDCOMPONENTOFDEVICEWITHID.QUANTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getCompound();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getComponent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort component3() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getCompound();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getComponent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort value3() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceswithoutidcomponentofdevicewithidRecord value1(UInteger value) {
        setCompound(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceswithoutidcomponentofdevicewithidRecord value2(UInteger value) {
        setComponent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceswithoutidcomponentofdevicewithidRecord value3(UShort value) {
        setQuantity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceswithoutidcomponentofdevicewithidRecord values(UInteger value1, UInteger value2, UShort value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DeviceswithoutidcomponentofdevicewithidRecord
     */
    public DeviceswithoutidcomponentofdevicewithidRecord() {
        super(Deviceswithoutidcomponentofdevicewithid.DEVICESWITHOUTIDCOMPONENTOFDEVICEWITHID);
    }

    /**
     * Create a detached, initialised DeviceswithoutidcomponentofdevicewithidRecord
     */
    public DeviceswithoutidcomponentofdevicewithidRecord(UInteger compound, UInteger component, UShort quantity) {
        super(Deviceswithoutidcomponentofdevicewithid.DEVICESWITHOUTIDCOMPONENTOFDEVICEWITHID);

        set(0, compound);
        set(1, component);
        set(2, quantity);
    }
}
