/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Devicerequests;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DevicerequestsRecord extends UpdatableRecordImpl<DevicerequestsRecord> implements Record11<UInteger, UInteger, Date, UByte, Date, UInteger, UInteger, UInteger, String, String, Byte> {

    private static final long serialVersionUID = -1378940700;

    /**
     * Setter for <code>trustalo.devicerequests.ID</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustalo.devicerequests.ID</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>trustalo.devicerequests.Applicant</code>.
     */
    public void setApplicant(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustalo.devicerequests.Applicant</code>.
     */
    public UInteger getApplicant() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>trustalo.devicerequests.Date</code>.
     */
    public void setDate(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustalo.devicerequests.Date</code>.
     */
    public Date getDate() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>trustalo.devicerequests.CurrentState</code>.
     */
    public void setCurrentstate(UByte value) {
        set(3, value);
    }

    /**
     * Getter for <code>trustalo.devicerequests.CurrentState</code>.
     */
    public UByte getCurrentstate() {
        return (UByte) get(3);
    }

    /**
     * Setter for <code>trustalo.devicerequests.LastUpdateDate</code>.
     */
    public void setLastupdatedate(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>trustalo.devicerequests.LastUpdateDate</code>.
     */
    public Date getLastupdatedate() {
        return (Date) get(4);
    }

    /**
     * Setter for <code>trustalo.devicerequests.LastUpdateWorker</code>.
     */
    public void setLastupdateworker(UInteger value) {
        set(5, value);
    }

    /**
     * Getter for <code>trustalo.devicerequests.LastUpdateWorker</code>.
     */
    public UInteger getLastupdateworker() {
        return (UInteger) get(5);
    }

    /**
     * Setter for <code>trustalo.devicerequests.Referee</code>.
     */
    public void setReferee(UInteger value) {
        set(6, value);
    }

    /**
     * Getter for <code>trustalo.devicerequests.Referee</code>.
     */
    public UInteger getReferee() {
        return (UInteger) get(6);
    }

    /**
     * Setter for <code>trustalo.devicerequests.Signer</code>.
     */
    public void setSigner(UInteger value) {
        set(7, value);
    }

    /**
     * Getter for <code>trustalo.devicerequests.Signer</code>.
     */
    public UInteger getSigner() {
        return (UInteger) get(7);
    }

    /**
     * Setter for <code>trustalo.devicerequests.TrelloLink</code>.
     */
    public void setTrellolink(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>trustalo.devicerequests.TrelloLink</code>.
     */
    public String getTrellolink() {
        return (String) get(8);
    }

    /**
     * Setter for <code>trustalo.devicerequests.Annotations</code>.
     */
    public void setAnnotations(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>trustalo.devicerequests.Annotations</code>.
     */
    public String getAnnotations() {
        return (String) get(9);
    }

    /**
     * Setter for <code>trustalo.devicerequests.Priority</code>.
     */
    public void setPriority(Byte value) {
        set(10, value);
    }

    /**
     * Getter for <code>trustalo.devicerequests.Priority</code>.
     */
    public Byte getPriority() {
        return (Byte) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<UInteger, UInteger, Date, UByte, Date, UInteger, UInteger, UInteger, String, String, Byte> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<UInteger, UInteger, Date, UByte, Date, UInteger, UInteger, UInteger, String, String, Byte> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Devicerequests.DEVICEREQUESTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return Devicerequests.DEVICEREQUESTS.APPLICANT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return Devicerequests.DEVICEREQUESTS.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field4() {
        return Devicerequests.DEVICEREQUESTS.CURRENTSTATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field5() {
        return Devicerequests.DEVICEREQUESTS.LASTUPDATEDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field6() {
        return Devicerequests.DEVICEREQUESTS.LASTUPDATEWORKER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field7() {
        return Devicerequests.DEVICEREQUESTS.REFEREE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field8() {
        return Devicerequests.DEVICEREQUESTS.SIGNER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Devicerequests.DEVICEREQUESTS.TRELLOLINK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Devicerequests.DEVICEREQUESTS.ANNOTATIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field11() {
        return Devicerequests.DEVICEREQUESTS.PRIORITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getApplicant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component3() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component4() {
        return getCurrentstate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component5() {
        return getLastupdatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component6() {
        return getLastupdateworker();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component7() {
        return getReferee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component8() {
        return getSigner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getTrellolink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getAnnotations();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component11() {
        return getPriority();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getApplicant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value4() {
        return getCurrentstate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value5() {
        return getLastupdatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value6() {
        return getLastupdateworker();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value7() {
        return getReferee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value8() {
        return getSigner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getTrellolink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getAnnotations();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value11() {
        return getPriority();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicerequestsRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicerequestsRecord value2(UInteger value) {
        setApplicant(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicerequestsRecord value3(Date value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicerequestsRecord value4(UByte value) {
        setCurrentstate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicerequestsRecord value5(Date value) {
        setLastupdatedate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicerequestsRecord value6(UInteger value) {
        setLastupdateworker(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicerequestsRecord value7(UInteger value) {
        setReferee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicerequestsRecord value8(UInteger value) {
        setSigner(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicerequestsRecord value9(String value) {
        setTrellolink(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicerequestsRecord value10(String value) {
        setAnnotations(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicerequestsRecord value11(Byte value) {
        setPriority(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicerequestsRecord values(UInteger value1, UInteger value2, Date value3, UByte value4, Date value5, UInteger value6, UInteger value7, UInteger value8, String value9, String value10, Byte value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DevicerequestsRecord
     */
    public DevicerequestsRecord() {
        super(Devicerequests.DEVICEREQUESTS);
    }

    /**
     * Create a detached, initialised DevicerequestsRecord
     */
    public DevicerequestsRecord(UInteger id, UInteger applicant, Date date, UByte currentstate, Date lastupdatedate, UInteger lastupdateworker, UInteger referee, UInteger signer, String trellolink, String annotations, Byte priority) {
        super(Devicerequests.DEVICEREQUESTS);

        set(0, id);
        set(1, applicant);
        set(2, date);
        set(3, currentstate);
        set(4, lastupdatedate);
        set(5, lastupdateworker);
        set(6, referee);
        set(7, signer);
        set(8, trellolink);
        set(9, annotations);
        set(10, priority);
    }
}
