/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Devicerequestsdevicemodels;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DevicerequestsdevicemodelsRecord extends UpdatableRecordImpl<DevicerequestsdevicemodelsRecord> implements Record3<UInteger, UInteger, UShort> {

    private static final long serialVersionUID = -619335769;

    /**
     * Setter for <code>trustalo.devicerequestsdevicemodels.RequestDevice</code>.
     */
    public void setRequestdevice(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustalo.devicerequestsdevicemodels.RequestDevice</code>.
     */
    public UInteger getRequestdevice() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>trustalo.devicerequestsdevicemodels.DeviceModel</code>.
     */
    public void setDevicemodel(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustalo.devicerequestsdevicemodels.DeviceModel</code>.
     */
    public UInteger getDevicemodel() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>trustalo.devicerequestsdevicemodels.Quantity</code>.
     */
    public void setQuantity(UShort value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustalo.devicerequestsdevicemodels.Quantity</code>.
     */
    public UShort getQuantity() {
        return (UShort) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<UInteger, UInteger> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UInteger, UShort> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UInteger, UShort> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Devicerequestsdevicemodels.DEVICEREQUESTSDEVICEMODELS.REQUESTDEVICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return Devicerequestsdevicemodels.DEVICEREQUESTSDEVICEMODELS.DEVICEMODEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UShort> field3() {
        return Devicerequestsdevicemodels.DEVICEREQUESTSDEVICEMODELS.QUANTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getRequestdevice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getDevicemodel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort component3() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getRequestdevice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getDevicemodel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort value3() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicerequestsdevicemodelsRecord value1(UInteger value) {
        setRequestdevice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicerequestsdevicemodelsRecord value2(UInteger value) {
        setDevicemodel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicerequestsdevicemodelsRecord value3(UShort value) {
        setQuantity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicerequestsdevicemodelsRecord values(UInteger value1, UInteger value2, UShort value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DevicerequestsdevicemodelsRecord
     */
    public DevicerequestsdevicemodelsRecord() {
        super(Devicerequestsdevicemodels.DEVICEREQUESTSDEVICEMODELS);
    }

    /**
     * Create a detached, initialised DevicerequestsdevicemodelsRecord
     */
    public DevicerequestsdevicemodelsRecord(UInteger requestdevice, UInteger devicemodel, UShort quantity) {
        super(Devicerequestsdevicemodels.DEVICEREQUESTSDEVICEMODELS);

        set(0, requestdevice);
        set(1, devicemodel);
        set(2, quantity);
    }
}
