/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.People;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PeopleRecord extends UpdatableRecordImpl<PeopleRecord> implements Record7<UInteger, UByte, String, Date, String, String, String> {

    private static final long serialVersionUID = 1994773936;

    /**
     * Setter for <code>trustalo.people.ID</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustalo.people.ID</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>trustalo.people.Category</code>.
     */
    public void setCategory(UByte value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustalo.people.Category</code>.
     */
    public UByte getCategory() {
        return (UByte) get(1);
    }

    /**
     * Setter for <code>trustalo.people.Name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustalo.people.Name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>trustalo.people.BirthDate</code>.
     */
    public void setBirthdate(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>trustalo.people.BirthDate</code>.
     */
    public Date getBirthdate() {
        return (Date) get(3);
    }

    /**
     * Setter for <code>trustalo.people.BirthLocation</code>.
     */
    public void setBirthlocation(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>trustalo.people.BirthLocation</code>.
     */
    public String getBirthlocation() {
        return (String) get(4);
    }

    /**
     * Setter for <code>trustalo.people.FiscalCode</code>.
     */
    public void setFiscalcode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>trustalo.people.FiscalCode</code>.
     */
    public String getFiscalcode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>trustalo.people.Annotations</code>.
     */
    public void setAnnotations(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>trustalo.people.Annotations</code>.
     */
    public String getAnnotations() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UInteger, UByte, String, Date, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UInteger, UByte, String, Date, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return People.PEOPLE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field2() {
        return People.PEOPLE.CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return People.PEOPLE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field4() {
        return People.PEOPLE.BIRTHDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return People.PEOPLE.BIRTHLOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return People.PEOPLE.FISCALCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return People.PEOPLE.ANNOTATIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component2() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component4() {
        return getBirthdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getBirthlocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getFiscalcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getAnnotations();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value2() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value4() {
        return getBirthdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getBirthlocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getFiscalcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getAnnotations();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PeopleRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PeopleRecord value2(UByte value) {
        setCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PeopleRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PeopleRecord value4(Date value) {
        setBirthdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PeopleRecord value5(String value) {
        setBirthlocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PeopleRecord value6(String value) {
        setFiscalcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PeopleRecord value7(String value) {
        setAnnotations(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PeopleRecord values(UInteger value1, UByte value2, String value3, Date value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PeopleRecord
     */
    public PeopleRecord() {
        super(People.PEOPLE);
    }

    /**
     * Create a detached, initialised PeopleRecord
     */
    public PeopleRecord(UInteger id, UByte category, String name, Date birthdate, String birthlocation, String fiscalcode, String annotations) {
        super(People.PEOPLE);

        set(0, id);
        set(1, category);
        set(2, name);
        set(3, birthdate);
        set(4, birthlocation);
        set(5, fiscalcode);
        set(6, annotations);
    }
}
