/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Printermodels;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrintermodelsRecord extends UpdatableRecordImpl<PrintermodelsRecord> implements Record3<UInteger, UByte, Short> {

    private static final long serialVersionUID = 972758925;

    /**
     * Setter for <code>trustalo.printermodels.DeviceModel</code>.
     */
    public void setDevicemodel(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustalo.printermodels.DeviceModel</code>.
     */
    public UInteger getDevicemodel() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>trustalo.printermodels.Tecnology</code>.
     */
    public void setTecnology(UByte value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustalo.printermodels.Tecnology</code>.
     */
    public UByte getTecnology() {
        return (UByte) get(1);
    }

    /**
     * Setter for <code>trustalo.printermodels.Resolution</code>.
     */
    public void setResolution(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustalo.printermodels.Resolution</code>.
     */
    public Short getResolution() {
        return (Short) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UByte, Short> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UByte, Short> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Printermodels.PRINTERMODELS.DEVICEMODEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field2() {
        return Printermodels.PRINTERMODELS.TECNOLOGY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field3() {
        return Printermodels.PRINTERMODELS.RESOLUTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getDevicemodel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component2() {
        return getTecnology();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component3() {
        return getResolution();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getDevicemodel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value2() {
        return getTecnology();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value3() {
        return getResolution();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrintermodelsRecord value1(UInteger value) {
        setDevicemodel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrintermodelsRecord value2(UByte value) {
        setTecnology(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrintermodelsRecord value3(Short value) {
        setResolution(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrintermodelsRecord values(UInteger value1, UByte value2, Short value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PrintermodelsRecord
     */
    public PrintermodelsRecord() {
        super(Printermodels.PRINTERMODELS);
    }

    /**
     * Create a detached, initialised PrintermodelsRecord
     */
    public PrintermodelsRecord(UInteger devicemodel, UByte tecnology, Short resolution) {
        super(Printermodels.PRINTERMODELS);

        set(0, devicemodel);
        set(1, tecnology);
        set(2, resolution);
    }
}
