/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Rammodels;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RammodelsRecord extends UpdatableRecordImpl<RammodelsRecord> implements Record3<UInteger, UShort, UByte> {

    private static final long serialVersionUID = -1045677180;

    /**
     * Setter for <code>trustalo.rammodels.DeviceModel</code>.
     */
    public void setDevicemodel(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustalo.rammodels.DeviceModel</code>.
     */
    public UInteger getDevicemodel() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>trustalo.rammodels.Capacity</code>.
     */
    public void setCapacity(UShort value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustalo.rammodels.Capacity</code>.
     */
    public UShort getCapacity() {
        return (UShort) get(1);
    }

    /**
     * Setter for <code>trustalo.rammodels.CapacityUnit</code>.
     */
    public void setCapacityunit(UByte value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustalo.rammodels.CapacityUnit</code>.
     */
    public UByte getCapacityunit() {
        return (UByte) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UShort, UByte> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UShort, UByte> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Rammodels.RAMMODELS.DEVICEMODEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UShort> field2() {
        return Rammodels.RAMMODELS.CAPACITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field3() {
        return Rammodels.RAMMODELS.CAPACITYUNIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getDevicemodel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort component2() {
        return getCapacity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component3() {
        return getCapacityunit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getDevicemodel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort value2() {
        return getCapacity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value3() {
        return getCapacityunit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RammodelsRecord value1(UInteger value) {
        setDevicemodel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RammodelsRecord value2(UShort value) {
        setCapacity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RammodelsRecord value3(UByte value) {
        setCapacityunit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RammodelsRecord values(UInteger value1, UShort value2, UByte value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RammodelsRecord
     */
    public RammodelsRecord() {
        super(Rammodels.RAMMODELS);
    }

    /**
     * Create a detached, initialised RammodelsRecord
     */
    public RammodelsRecord(UInteger devicemodel, UShort capacity, UByte capacityunit) {
        super(Rammodels.RAMMODELS);

        set(0, devicemodel);
        set(1, capacity);
        set(2, capacityunit);
    }
}
