/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Screenresolutions;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScreenresolutionsRecord extends UpdatableRecordImpl<ScreenresolutionsRecord> implements Record4<UByte, UShort, UShort, UByte> {

    private static final long serialVersionUID = 751498830;

    /**
     * Setter for <code>trustalo.screenresolutions.ID</code>.
     */
    public void setId(UByte value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustalo.screenresolutions.ID</code>.
     */
    public UByte getId() {
        return (UByte) get(0);
    }

    /**
     * Setter for <code>trustalo.screenresolutions.Width</code>.
     */
    public void setWidth(UShort value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustalo.screenresolutions.Width</code>.
     */
    public UShort getWidth() {
        return (UShort) get(1);
    }

    /**
     * Setter for <code>trustalo.screenresolutions.Height</code>.
     */
    public void setHeight(UShort value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustalo.screenresolutions.Height</code>.
     */
    public UShort getHeight() {
        return (UShort) get(2);
    }

    /**
     * Setter for <code>trustalo.screenresolutions.AspectRatio</code>.
     */
    public void setAspectratio(UByte value) {
        set(3, value);
    }

    /**
     * Getter for <code>trustalo.screenresolutions.AspectRatio</code>.
     */
    public UByte getAspectratio() {
        return (UByte) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UByte> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UByte, UShort, UShort, UByte> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UByte, UShort, UShort, UByte> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field1() {
        return Screenresolutions.SCREENRESOLUTIONS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UShort> field2() {
        return Screenresolutions.SCREENRESOLUTIONS.WIDTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UShort> field3() {
        return Screenresolutions.SCREENRESOLUTIONS.HEIGHT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field4() {
        return Screenresolutions.SCREENRESOLUTIONS.ASPECTRATIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort component2() {
        return getWidth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort component3() {
        return getHeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component4() {
        return getAspectratio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort value2() {
        return getWidth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort value3() {
        return getHeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value4() {
        return getAspectratio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScreenresolutionsRecord value1(UByte value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScreenresolutionsRecord value2(UShort value) {
        setWidth(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScreenresolutionsRecord value3(UShort value) {
        setHeight(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScreenresolutionsRecord value4(UByte value) {
        setAspectratio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScreenresolutionsRecord values(UByte value1, UShort value2, UShort value3, UByte value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScreenresolutionsRecord
     */
    public ScreenresolutionsRecord() {
        super(Screenresolutions.SCREENRESOLUTIONS);
    }

    /**
     * Create a detached, initialised ScreenresolutionsRecord
     */
    public ScreenresolutionsRecord(UByte id, UShort width, UShort height, UByte aspectratio) {
        super(Screenresolutions.SCREENRESOLUTIONS);

        set(0, id);
        set(1, width);
        set(2, height);
        set(3, aspectratio);
    }
}
