/*
 * This file is generated by jOOQ.
*/
package it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.records;


import it.trashwarecesena.trustalodesktopclient.repository.mapper.jooq.trustalodb.trustalo.tables.Workers;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkersRecord extends UpdatableRecordImpl<WorkersRecord> implements Record3<UInteger, UByte, Byte> {

    private static final long serialVersionUID = -950344;

    /**
     * Setter for <code>trustalo.workers.Person</code>.
     */
    public void setPerson(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustalo.workers.Person</code>.
     */
    public UInteger getPerson() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>trustalo.workers.Category</code>.
     */
    public void setCategory(UByte value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustalo.workers.Category</code>.
     */
    public UByte getCategory() {
        return (UByte) get(1);
    }

    /**
     * Setter for <code>trustalo.workers.CurrentlyWorking</code>.
     */
    public void setCurrentlyworking(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustalo.workers.CurrentlyWorking</code>.
     */
    public Byte getCurrentlyworking() {
        return (Byte) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UByte, Byte> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UByte, Byte> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Workers.WORKERS.PERSON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field2() {
        return Workers.WORKERS.CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return Workers.WORKERS.CURRENTLYWORKING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getPerson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component2() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component3() {
        return getCurrentlyworking();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getPerson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value2() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getCurrentlyworking();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorkersRecord value1(UInteger value) {
        setPerson(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorkersRecord value2(UByte value) {
        setCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorkersRecord value3(Byte value) {
        setCurrentlyworking(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorkersRecord values(UInteger value1, UByte value2, Byte value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkersRecord
     */
    public WorkersRecord() {
        super(Workers.WORKERS);
    }

    /**
     * Create a detached, initialised WorkersRecord
     */
    public WorkersRecord(UInteger person, UByte category, Byte currentlyworking) {
        super(Workers.WORKERS);

        set(0, person);
        set(1, category);
        set(2, currentlyworking);
    }
}
