package todo.vm;

import java.util.Objects;

import todo.utils.Checks;

/**
 * The Value class represents a value generated by the VM. It can be either a
 * number, an character or empty. It's used instead of an optional Integer since
 * the latter doesn't allow to store whether the number represents an ASCII
 * character or not.
 */
public final class Value {
    private final Integer storedValue;
    private final boolean isValueAscii;

    private Value(final Integer value, final boolean ascii) {
        this.storedValue = value;
        this.isValueAscii = ascii;
    }

    /**
     * @param value the number stored in the Value
     * @return a Value storing the provided number
     */
    public static Value number(final int value) {
        return new Value(value, false);
    }

    /**
     * @param value the character stored in the Value
     * @return a Value storing the ASCII representation of the provided character
     */
    public static Value ascii(final char value) {
        return new Value((int) value, true);
    }

    /**
     * @return a Value storing nothing
     */
    public static Value empty() {
        return new Value(null, false);
    }

    /**
     * @return either the stored number or the ASCII representation of the stored
     *         character.
     * @throws NullPointerException if the Value is empty
     */
    public int asNumber() {
        return this.storedValue;
    }

    /**
     * @return true if the value is not empty
     */
    public boolean isPresent() {
        return this.storedValue != null;
    }

    /**
     * @return true if the value is an ASCII-represented character
     */
    public boolean isASCII() {
        return this.isValueAscii;
    }

    /**
     * Return the value if it's present, otherwise throw the provided exception.
     *
     * @param <E> the type of the exception to be thrown
     * @param type the class of the exception to be thrown
     * @return the Value
     * @throws E the exception that may be thrown
     */
    public <E extends Exception> Value orThrow(final Class<E> type) throws E {
        Checks.require(isPresent(), type);
        return this;
    }

    /**
     * Return the value if it's present, otherwise throw the provided exception.
     *
     * @param <E> the type of the exception to be thrown
     * @param type the class of the exception to be thrown
     * @param message a message to be associated with the exception thrown
     * @return the Value
     * @throws E the exception that may be thrown
     */
    public <E extends Exception> Value orThrow(final Class<E> type, final String message) throws E {
        Checks.require(isPresent(), type, message);
        return this;
    }

    @Override
    public boolean equals(final Object other) {
        // The values must be both empty or must have the same value and representation
        // to be equal
        return other instanceof Value
                && ((this.storedValue == null && ((Value) other).storedValue == null)
                        || this.storedValue.equals(((Value) other).storedValue))
                && this.isValueAscii == ((Value) other).isValueAscii;
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.storedValue, this.isValueAscii);
    }

    @Override
    public String toString() {
        if (this.storedValue == null) {
            return "Value(empty)";
        } else if (this.isValueAscii) {
            return "Value(ascii: " + Character.toString((char) (int) this.storedValue) + ")";
        } else {
            return "Value(number: " + Integer.toString(this.storedValue) + ")";
        }
    }
}
