package utils;

/**
 * Enum of film and book genre taken from the web.
 * https://it.wikipedia.org/wiki/Generi_cinematografici
 * http://generi.librimondadori.it
 *
 * @author Edoardo
 *
 */
public enum ItemGenre {

  /**
   *
   */
  ART_FILM_MUSIC_ENTERTAINMENT, CURRENT_NEWS_REPORTS, WELLNESS_SELFELPH_LIFESTYLE, BIOGRAPHIES, CLASSICAL_CRITICISM, KITCHEN, FANTASY, GRAPHICNOVEL, HOBBY, FASHION, FICTION_MODERN_CONTEMPORARY, POETRY, POLICY, PSYCOLOGY_SOCIOLOGY, RELIGION, LOVE_NOVELS, TECHNOLOGY_SCIENCE, SPORT, ADVENTURE_HISTORY, HUMOR, TRAVEL_GUIDE, ANIMATION, ADVENTURE, BIOGRAPHICAL, COMEDY, DOCUMENTARY, DRAMA, SCI_FI, WAR, HORROR, MUSICAL, HISTORICAL, THRILLER, WESTERN

}
