package controller.gui.leaderboard;

import java.io.IOException;
import javafx.fxml.FXML;

/**
 * 
 * The controller associated to the leaderboard's gui and fxml file. 
 *
 */
public interface GUILeaderboardController {

    /**
     * The handler for the click event generated by the 'back' button.
     * Shows the menu's scene.
     * 
     * @throws IOException
     *      if the name of the fxml is mispelled or if it doesn't exist
     */
    @FXML
    void backBtnOnClickHandler() throws IOException;

    /**
     * The handler for the click event generated by the 'info' button.
     * Shows a hidden panel that explains how the score is computed.
     * 
     * @throws IOException
     *      if the name of the fxml is mispelled or if it doesn't exist
     */
    @FXML
    void infoBtnOnClickHandler() throws IOException;
}
