/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.2/userguide/building_java_projects.html in the Gradle documentation.
 */
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
plugins {
    java
    application
    id("com.github.johnrengelman.shadow") version "8.1.1"

    id("org.danilopianini.unibo-oop-gradle-plugin") version "1.1.71"
}

java { toolchain { languageVersion.set(JavaLanguageVersion.of(21)) } }


repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.mainPackage.App"
}

tasks.withType<ShadowJar> {
    archiveFileName.set("OOP24-SonicTheHedgehog-all.jar")
    mergeServiceFiles()
}

tasks.named("build") {
    dependsOn(tasks.named("shadowJar"))
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
      testLogging {
        events("passed", "skipped", "failed")
        showStandardStreams = true
    }
}
