package oop.focus.finance.model;

import javafx.collections.ObservableSet;
import oop.focus.common.Repetition;
import oop.focus.db.Dao;
import oop.focus.db.DataSource;
import oop.focus.db.exceptions.DaoAccessException;
import org.joda.time.LocalDate;
import org.joda.time.LocalDateTime;
import org.joda.time.LocalTime;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Function;
import java.util.function.Predicate;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Immutable implementation of a transaction manager.
 */
public class TransactionManagerImpl implements TransactionManager {

    private final Dao<Transaction> transactions;

    public TransactionManagerImpl(final DataSource db) {
        this.transactions = db.getTransactions();
    }

    /**
     * Saves a transaction in the database.
     * It is not possible to add a transaction at a future date.
     *
     * @param transaction that is saved
     */
    @Override
    public final void add(final Transaction transaction) {
        if (!transaction.getDate().isAfter(LocalDateTime.now())) {
            try {
                this.transactions.save(transaction);
            } catch (final DaoAccessException e) {
                e.printStackTrace();
            }
        } else {
            throw new UnsupportedOperationException();
        }
    }

    /**
     * Removes a transaction from the database.
     *
     * @param transaction being deleted
     */
    @Override
    public final void remove(final Transaction transaction) {
        try {
            this.transactions.delete(transaction);
        } catch (final DaoAccessException e) {
            e.printStackTrace();
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public final void update(final Transaction transaction) {
        this.remove(transaction);
        this.add(transaction);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public final void stopRepeat(final Transaction subscription) {
        subscription.stopRepeat();
        this.update(subscription);
    }

    /**
     * @return the list of all transactions
     */
    @Override
    public final ObservableSet<Transaction> getElements() {
        return this.transactions.getAll();
    }

    @Override
    public final List<Transaction> getSubscriptions() {
        return this.filteredTransactions(Transaction::isToBeRepeated);
    }

    @Override
    public final List<Transaction> getGeneratedTransactions(final LocalDate date) {
        return this.getSubscriptions().stream()
                .flatMap(t -> this.generateNext(t, date).stream()).collect(Collectors.toList());
    }

    @Override
    public final int monthlyExpense() {
        return this.computeExpense(Repetition::getPerMonthFunction);
    }

    @Override
    public final int yearlyExpense() {
        return this.computeExpense(Repetition::getPerYearFunction);
    }

    /**
     * Given a list of transactions, returns a list filtered by a predicate.
     *
     * @param predicate by which transactions are filtered
     * @return a filtered list of transactions
     */
    private List<Transaction> filteredTransactions(final Predicate<Transaction> predicate) {
        return this.transactions.getAll().stream().filter(predicate).collect(Collectors.toList());
    }

    /**
     * Calculates all transactions generated by a transaction to repeat over time,
     * up to the date passed as a parameter.
     *
     * @param t subscription for which we want to calculate the transactions to be generated
     * @param date until which we want to calculate the transactions to repeat
     * @return a list of all transactions generated
     */
    private List<Transaction> generateNext(final Transaction t, final LocalDate date) {
        if (date.toLocalDateTime(LocalTime.MIDNIGHT).isBefore(t.getNextRenewal().toLocalDateTime(LocalTime.MIDNIGHT))) {
            return new ArrayList<>();
        }
        t.stopRepeat();
        final var transaction = new TransactionImpl(t.getDescription(), t.getCategory(),
                t.getNextRenewal().toLocalDateTime(LocalTime.MIDNIGHT), t.getAccount(), t.getAmount(), t.getRepetition());
        return Stream.concat(List.of(transaction).stream(),
                this.generateNext(transaction, date).stream()).collect(Collectors.toList());
    }

    /**
     * Method that calculates the cost of active subscriptions based on a function.
     *
     * @param function that given a repetition returns its function to calculate the amount
     * @return the total calculated amount
     */
    private int computeExpense(final Function<Repetition, Function<Integer, Integer>> function) {
        return this.transactions.getAll().stream()
                .filter(Transaction::isToBeRepeated)
                .map(t -> function.apply(t.getRepetition()).apply(t.getAmount()))
                .reduce(0, Integer::sum);
    }
}
